### ISSUE TITLE
Helm-Templating: if $.Capabilities...

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#1009]
Hi,

just wanted to ask if the helm-support is supposed to work with if/else depending on the clusters capabilities? Didn't see any mention of this, these never seem to get templated.
If not, it might be useful for others to add a note to the docs.

```
{{- with .Values.monitoring.serviceMonitor }}
{{- if and ($.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "loki.fullname" $ }}
  names
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
```

**Comment by Duologic** [comment]
No, Helm within Tanka does not talk directly to the cluster. Tanka simply runs `helm template`.

**Comment by Duologic** [comment]
Just looked it up, seems like you can use `apiVersions` and `kubeVersion` to manipulate the capabilities during Tanka execution, but you'll need to know this information upfront.

```
{
  grafana: helm.template("grafana", "./charts/grafana", {
    namespace: "monitoring",
    values: {
      persistence: { enabled: true }
    },
    // Equivalent to: --api-versions v1 --api-versions apps/v1
    apiVersions: ['v1', 'apps/v1']
    // Equivalent to: --kube-version v1.20.0
    kubeVersion: 'v1.20.0'
    // Equivalent to: --no-hooks
    noHooks: true,
}
```

These values correspond to the Options here: https://helm.sh/docs/helm/helm_template/#options

**Comment by strowi** [comment]
Ah thank you vor the workaround!
