### ISSUE TITLE
container cannot start

### ISSUE THREAD

**Issue by majdiredifi** [grafana/tanka#1015]
I built a tanka docker image with the [dockerfile](https://github.com/grafana/tanka/blob/main/Dockerfile)
the container cannot start, with the following error:
Error: Error: unknown subcommand sh Usage: tk [command] Available Commands: apply       apply the configuration to the cluster show        jsonnet as yaml diff        differences between the configuration and the cluster prune       delete resources removed from Jsonnet delete      delete the environment from cluster env         manipulate environments status      display an overview of the environment, including contents and metadata. export      export environments found in path(s) fmt         format Jsonnet code lint        lint Jsonnet code eval        evaluate the jsonnet to json init        Create the directory structure tool        handy utilities for working with jsonnet complete    install CLI completions Flags: -h, --help   help for tk Use "tk [command] --help" for more information about a command. Cleaning up project directory and file based variables 00:02 ERROR: Job failed: exit code 1
![image](https://github.com/grafana/tanka/assets/47420575/73fd3d40-ef4a-415e-a114-45e0421bf95d)

plz help has resolved

**Comment by zerok** [comment]
How are you starting the container?

**Comment by majdiredifi** [comment]
Hi
I found the solution here https://gitlab.com/gitlab-org/gitlab-foss/-/issues/65110#note_198073241
just put: entrypoint: [""]
Thks
