### ISSUE TITLE
Add TANKA_PAGER env var

### ISSUE THREAD

**Issue by rrotter** [grafana/tanka#1028]
Could you consider (or would you accept a PR for) adding support for a TANKA_PAGER env var in addition to PAGER in case a user wants to use a different pager for `tk` than for other tools? This is particularly of interest when using in-pager syntax highlighting.

Currently I'm using an alias to do this, but it's a bit clunky: `alias tk='PAGER="bat --language=yaml" tk'`

**Comment by Elfo404** [comment]
Seems like a reasonable thing to add, would you be interested in submitting a PR?
