### ISSUE TITLE
`tk show` completion prints debug info to terminal

### ISSUE THREAD

**Issue by rrotter** [grafana/tanka#1048]
`tk show <tab>` prints:
```
$ tk show {"level":"debug","parallelism":6,"paths":1,"time":"2024-05-30T00:52:04-04:00","message":"Finding Tanka environments"}
```

I'm seeing the same behavior on macos and linux, bash and zsh. This appears to be a regression in the current release: `tk version v0.27.1`. I'm not seeing this issue on `v0.26.0`.

**Comment by zerok** [comment]
That's weird. This would imply that the `--log-level` flag is set to debug (or higher). Could it be that you set this in your bash/zsh configuration?

**Comment by rrotter** [comment]
There doesn't appear to be any env var in either tanka or zerolog that sets the log level, so I'm not sure how that would be possible outside of something like `alias tk='tk --log-level=debug'`, which I'm not doing:
```
~ % type -a tk
tk is /opt/homebrew/bin/tk
```

To be doubly sure it's not my environment I created a new Debian vm with nothing at all configured and ran the following:
```
# as root
curl -Lso /usr/local/bin/tk https://github.com/grafana/tanka/releases/download/v0.27.1/tk-linux-amd64
chmod +x /usr/local/bin/tk
useradd -m --shell=/bin/bash testuser

# as testuser
tk complete
# logout and in again
mkdir tktest; cd tktest
tk init
tk show<TAB> # produces the same debug dump as above
```

Also reconfirmed with this method that completion works as expected on `v0.26.0`, this debug info is only generated on `v0.27.1`.

**Comment by rrotter** [comment]
I think I figured this out. `git bisect` shows that 3f93e7178a is the first affected version. Nothing there touches `zerolog.SetGlobalLevel`, but it does include the `log.Debug` call that I'm seeing on the terminal. I think there are actually two issues here:

1. The default logging level is info. This was probably fine in the past, but there's been a lot of logging added since 0.2.6, resulting in log spam like this:
```
$ tk env ls
{"level":"info","environments":1,"ms_to_find_jsonnet_files":0.436964,"ms_to_find_environments":1.570647,"time":"2024-06-05T17:16:53Z","message":"Found Tanka environments"}
NAME                    NAMESPACE    SERVER
environments/default    default
```

2. There is no default log level set if we never reach the `SetGlobalLevel` call in `addCommandsWithLogLevelOption()`. When this happens `tk` logs at the trace level, which is the case with the completer.
