### ISSUE TITLE
`tk export` broken on Windows

### ISSUE THREAD

**Issue by systemtrap** [grafana/tanka#1055]
Since #841 `tk export` breaks on Windows.

godirwalk changed its behavior in karrick/godirwalk#68. godirwalk seems unmaintained as karrick/godirwalk#70 is an open issue for more than a year.

**Comment by zerok** [comment]
Thank you for reporting this 🙂 

Judging by the code that uses godirwalk the reason for adding it was performance implications of `filepath.Walk`. IMO it would be worth a try to benchmark the current implementation against one using `filepath.WalkDir` and switch to that if they are at least comparable.

**Comment by zerok** [comment]
@systemtrap if you have the time, could you perhaps please try https://github.com/grafana/tanka/pull/1058 if that works for you?

**Comment by systemtrap** [comment]
I'm sorry., I missed the message. I'll check in the next couple of days.

**Comment by zerok** [comment]
No worries and thank you 🙂

**Comment by systemtrap** [comment]
Works fine for me.

**Comment by zerok** [comment]
Awesome, thank you :) Then this will probably make it into the next release.
