### ISSUE TITLE
Bug: `tk apply --auto-approve=always` with no changes returns non-zero exit code.

### ISSUE THREAD

**Issue by ricardbejarano** [grafana/tanka#1059]
Tanka version:
```
$ tk --version
2024/06/08 22:20:20 tk version 0.26.0
```

Error:
```
$ tk apply --auto-approve=if-no-changes environments/default  # same thing happens with --auto-approve=always
Warning: There are no differences. Your apply may not do anything at all.
error: no objects passed to apply
Error: exit status 1
Error: exit status 1
$ echo $?
1
```

I'd expect this not to fail, particularly if `--auto-approve` is `always` or `if-no-changes`.

**Comment by zerok** [comment]
Hi 🙂 Does this also happen with Tanka 0.27.1?

**Comment by ricardbejarano** [comment]
Yup:
```
$ tk --version
2024/06/12 08:39:44 tk version 0.27.1
$ tk apply --auto-approve=always environments/default
Warning: There are no differences. Your apply may not do anything at all.
error: no objects passed to apply
Error: exit status 1
$ echo $?
1
$
```

**Comment by zerok** [comment]
Thank you for checking 🙂 Will add it to our backlog 🙂

**Comment by guicaulada** [comment]
While investigating this issue I noticed the issue doesn't happen necessarily when there are no changes, but when there are no objects.

For example using the same environments as the [tutorial](https://tanka.dev/tutorial/environments/) when applying:
```jsonnet
(import 'prom-grafana/prom-grafana.libsonnet') +
{
  // again, we only want to patch, not replace, thus +::
  _images+:: {
    // we update this one entirely, so we can replace this one (:)
    promgrafana: {
      prometheus: 'prom/prometheus:v2.14',
      grafana: 'grafana/grafana:6.5.2',
    },
  },
}
```

With no changes, applying with auto-approve `always` or `if-no-changes` exits with exit-code 0 and gives me the following output:
```
Warning: There are no differences. Your apply may not do anything at all.
service/grafana unchanged
service/prometheus unchanged
deployment.apps/grafana unchanged
deployment.apps/prometheus unchanged
```

However if I try to apply an environment with no objects, for example:
```
{}
```

It gives me the same error you have been having:
```
Warning: There are no differences. Your apply may not do anything at all.
error: no objects passed to apply
Error: exit status 1
```

For me this behaviout makes sense, when there are no changes there's no error and the exit code is 0 but if there are no objects to be applied something is probably wrong and returning with an error makes sense in this case.

**Comment by ricardbejarano** [comment]
> For me this behaviout makes sense, when there are no changes there's no error and the exit code is 0 but if there are no objects to be applied something is probably wrong and returning with an error makes sense in this case.

But an empty set is still a set. I think the behaviour should be consistent.

**Comment by guicaulada** [comment]
The behavior is consistent to `kubectl`, using an empty file:
```
> kubectl apply -f test.yml
error: no objects passed to apply
> echo $?
1
```

**Comment by ricardbejarano** [comment]
Hmm.. okay, fair enough.
I'll close this.
