### ISSUE TITLE
tk diff: duplicate ports when port changes

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#1105]
Hi,

i noticed the following error when changing the port of a service:

1. `tk init`
2. Add this to `main.jsonnet`
```
{
  apiVersion: 'v1',
  kind: 'Service',
  metadata: {
    name: 'keycloak',
    namespace: 'default',
  },
  spec: {
    ports: [
      {
        name: 'http',
        port: 80,
        protocol: 'TCP',
        targetPort: 8080,
      },
    ],
    selector: {
      'app.kubernetes.io/name': 'keycloak',
    },
  },
}
```
3. Deploy.
4. change the port from `80` to `8099`
5. Run  `tk diff --diff-strategy validate --with-prune --exit-zero --log-level warn environments/default` and see the following error:
```
The Service "keycloak" is invalid: spec.ports[1].name: Duplicate value: "http"
Error: exit status 2
```

I thought this might be a kubctl-bug, but doing the same with pure yaml and running `kubectl diff service.yaml` shows the correct output:

```
~> k diff -f service.yml
diff -uN /tmp/LIVE-3154311126/v1.Service.default.keycloak /tmp/MERGED-3713640241/v1.Service.default.keycloak
--- /tmp/LIVE-3154311126/v1.Service.default.keycloak	2024-07-16 18:12:56.642154641 +0200
+++ /tmp/MERGED-3713640241/v1.Service.default.keycloak	2024-07-16 18:12:56.646154726 +0200
@@ -13,7 +13,7 @@
   ipFamilyPolicy: SingleStack
   ports:
   - name: http
-    port: 8099
+    port: 80
     targetPort: 8080
   selector:
     app.kubernetes.io/name: keycloak
```

**Comment by zerok** [comment]
Hi 🙂 

If you use `--diff-strategy validate` you are actually using `kubectl diff --server-side` under the hood, and this also fails in that case.

```
❯ kubectl diff -f v1.Service-keycloak.yaml --server-side
The Service "keycloak" is invalid: spec.ports[1].name: Duplicate value: "http"
```

This is a bug in kubectl or the diff API of Kubernetes itself, I'm afraid. Sorry 🙂

**Comment by strowi** [comment]
@zerok ah missed the `--server-side` option. Thank you for the explanation and sorry for the fuss. ;)

**Comment by zerok** [comment]
No worries 🙂 Glad it wasn't us 🤣
