### ISSUE TITLE
add `metadata.name` to reconciliation criteria

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#113]
Nice suggestion by @lawrencejones: `metadata.name` is crucial to every Kubernetes object. It should be added to our `walkJSON` func which identifies valid objects to extract them. 

Furthermore it would make sense to not only check for the presence of `apiVersion`, `kind` and `metadata.name`, but also validate them (check that they are strings)

**Comment by anarcher** [comment]
Hi, When I try to use tanka with kube-prometheus jsonnets, Resources  like `rbac.authorization.k8s.io/v1/RoleBindingList` could be failed like below: 
```
reconciling: flattening manifests: .prometheus-roleSpecificNamespaces missing or invalid fields: metadata, metadata.name
```
I am not sure but the `RoleBindingList`or other `List` resurces  doesn't have  `metadata.name` field.  
How do I handle this list resources with tanka? :-)


```
 "prometheus-roleSpecificNamespaces": {
      "apiVersion": "rbac.authorization.k8s.io/v1",
      "items": [
         {
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "kind": "Role",
            "metadata": {
               "name": "prometheus-k8s",
               "namespace": "default"
            },
            "rules": [
               {
                  "apiGroups": [
                     ""
                  ],
                  "resources": [
                     "services",
                     "endpoints",
                     "pods"
                  ],
                  "verbs": [
                     "get",
                     "list",
                     "watch"
                  ]
               }
            ]
         },
   ],
   "kind": "RoleList"
}
```

**Comment by sh0rez** [comment]
Oh, so there is another `List` type ... wtf. Are they documented anywhere so we can exclude all of them from the `metadata.name` criteria?

**Comment by anarcher** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#listmeta-v1-meta
https://github.com/kubernetes/apimachinery/blob/cce7a330881575ce32ac9f50852de77237194a55/pkg/apis/meta/v1/types.go#L60:6
The `ListMeta` doesn't have `metadata.name`. humm. 
Can we check the type of meta of resources during reconciliation?

**Comment by sh0rez** [comment]
@anarcher judging from your error message above, does this issue already happen? Because afaict `metadata.name` is not yet a cirtieria ...

**Comment by sh0rez** [comment]
@anarcher I have been able to reproduce your issue and pushed a fix accordingly: Once merged, Tanka won't expect `metadata` to be present on objects that end in `List` anymore. This should be sufficient for most (all?) cases.

Furthermore, as we have discovered, `metadata` is NOT mandatory to all objects .. so this one here is obsolete and should not be done IMHO. Closing

**Comment by anarcher** [comment]
@sh0rez Thanks! I agree that   `.*List` skips to check `metadata` field is good in most cases :-)
