### ISSUE TITLE
Cannot read yaml with block string or string with new lines.

### ISSUE THREAD

**Issue by blmhemu** [grafana/tanka#1142]
Cannot parse yaml files with newlines in strings.
ex:
```yaml
cert: |
  ----BEGIN----
  ----END-----
```
Tried with
```
cert: '----BEGIN---\n....\n----END----'
```

still not working

**Comment by blmhemu** [comment]
Workaround for the wanderers - base64 encode the multiline string (and use `std.base64` in jsonnet if you want actual value)

**Comment by zerok** [comment]
How are you loading the YAML data? `std.parseYaml(importstr "dummy.yaml")` seems to work for me 🙂

**Comment by zerok** [comment]
Will close this for now. If necessary, please reopen/leave a comment 🙂
