### ISSUE TITLE
Allow to disable kubectl validation

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#115]
quoting @lawrencejones:
> Worth considering if you want to enable other kubectl flags. Several popular libraries (I'm looking at you, cert-manager) currently require you to set --validate=false to apply the manifests. You could use jsonnet to make the vendored resources valid, but I think many people may want to follow the official docs?

We should allow to invoke `kubectl` with `--validate=false` by exposing that exact flag on the `tk apply` operation.

Note: This should be done after #111 is merged

**Comment by cezkuj** [comment]
I would like to pick it up. Seems like depending PR is merged so doesn't seem like there are any other blockers
