### ISSUE TITLE
tk diff -t requires the resource type to be lower case

### ISSUE THREAD

**Issue by replay** [grafana/tanka#126]
when doing `tk show` it shows me resource types, such as `ConfigMap` in camel case. but when i try to do `tk diff` and use the `-t` parameter to select one specific resource i need to specify the resource type in lower case (`configmap`) for it to work, when i write it `ConfigMap` then `tk` seems to not find the resource. I think this should be case insensitive.

**Comment by sh0rez** [comment]
Already fixed, needs review though
