### ISSUE TITLE
Release notes use wrong image tag for docker tanka

### ISSUE THREAD

**Issue by chancez** [grafana/tanka#128]
The https://github.com/grafana/tanka/releases/tag/v0.6.0 release says you can get the docker image using

```
$ docker pull grafana/tanka:v0.6.0
```

But the `v0.6.0` tag doesn't exist, but `0.6.0-amd64` does. It seems when you switched to support multiple arches you began suffixing the image tags. `.drone/release-note.md` is what looks like it needs updating.

**Comment by sh0rez** [comment]
Hi, it looks like bundling all images in the final manifest is broken for tag releases at the moment ... I will look into it. 

And you are correct, the tag name is wrong anyways, it should be called `grafana/tanka:0.6.0`

**Comment by sh0rez** [comment]
Docker packaging is indeed broken, will fix for the next release. Keep an eye on https://github.com/grafana/tanka/issues/129 which is tracking this issue :D
