### ISSUE TITLE
 manifest for grafana/tanka:v0.6.0 not found

### ISSUE THREAD

**Issue by dohnto** [grafana/tanka#129]
In release page (https://github.com/grafana/tanka/releases) there are instructions:

> $ docker pull grafana/tanka:v0.6.0

Running this command fails with
```
$ docker pull grafana/tanka:v0.6.0
Error response from daemon: manifest for grafana/tanka:v0.6.0 not found
```

In dockerhub, I can see, that you started suffixing images with CPU architectures (arm, amd64, ...). Please adjust release notes or create additional docker images.

**Comment by sh0rez** [comment]
Apparently I broke drone auto tagging in https://github.com/grafana/tanka/pull/90.
Will fix for the next release, sorry for the inconvenience!
