### ISSUE TITLE
tool to set API server url from kubeconfig

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#137]
When we first set up a Tanka environment, we need to extract the API server URL from our kubeconfig.

For the current context and default namespace, this should do it:

```
APISERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
sed -i 's#"apiServer": ""#"apiServer": "'${APISERVER}'"#' environments/default/spec.json
```

If we are a new user to Kubernetes, this could confuse us. What if we were able to say something like this:

```
tk env set-server /environments/default  # set env from default kubeconfig context
tk env set-server /environments/default --context my-context # set env from specific kubeconfig context
```

Ramp up into Tanka would be substantially easier.

**Comment by sh0rez** [comment]
I suggest extending `tk env set` by `--server-from-context` (or even `--context`) instead, as it plays nicer with the current approach (`tk env set --server IP)

**Comment by sh0rez** [comment]
This has been done in #184
