### ISSUE TITLE
Access to Tanka metadata

### ISSUE THREAD

**Issue by Grannath** [grafana/tanka#161]
Hi, thanks for this project! I just spent way too much time with Helm, and this looks to solve a bunch of my issues with it.

Something I noticed is still missing is access to the metadata inside of the jsonnet files. I want e.g. to include the environment name as a label. As far as I can tell, so far I have to ask for the environment name again in the config. It would be great if this is available always under some standardized name, similar to how Helm includes this as predefined variables.

**Comment by sh0rez** [comment]
Yes, we can certainly provide that data to Jsonnet. We wanted to introduce a standard library for Tanka anyways (#105), so WDYT about the following syntax:

```jsonnet
local tk = import "tk";

{
  whatever: tk.env.metadata.labels.app
}
```

**Comment by cyriltovena** [comment]
> Yes, we can certainly provide that data to Jsonnet. We wanted to introduce a standard library for Tanka anyways (#105), so WDYT about the following syntax:
> 
> ```jsonnet
> local tk = import "tk";
> 
> {
>   whatever: tk.env.metadata.labels.app
> }
> ```

Really like this feature specially for getting the namespace.

**Comment by malcolmholmes** [comment]
@sh0rez could we use something similar to get the default set of 'kinds' for deletions? (#131)

**Comment by Grannath** [comment]
@sh0rez MR looks great, thanks!

One more thing though. I wonder if it is possible to figure out the "position" of a resource in my files. So basically the directory names and the nodes above the actual resource.

Directories should be easy, since tanka assumes a certain layout. So it should be possible to pass a list of strings in as well to give the directories. This would potentially allow for some deduplication of information.

Even better would be access to the parent nodes, which usually will contain names for the resources. But I guess resolution which are K8s resources and which "just" json can only be done after expansion. Is it possible with pure jsonnet reflection to traverse the structure upwards? :thinking:

**Comment by malcolmholmes** [comment]
There is a concept of "json path". We have talked about exposing that. It is helpful when you want to override something but can't find it in the resultant json (which you can see with `tk eval`). We've talked about adding that as a label/annotation on the resources themselves (I think that's in the deletions/pruning PR). Also, @sh0rez did suggest adding json path to the output of `tk status`, which would be helpful. And could help you identify the json location of a resource.

Regarding directory names, are you talking about the equivalent of `__file__` or `__dir__`, i.e. the path to the current file?

I'm not entirely sure I grasp the problem you are trying to solve yet.

**Comment by sh0rez** [comment]
@Grannath if you want to achieve the following: „I have Deployment x, which file created it?“ .. I guess this won‘t be possible, because Jsonnet is lazy evaluated. 

Can we do something about this, @sbarzowski? IE „jump to definition“ when using constructs like „$.core.v1.whatever“ and such

**Comment by Grannath** [comment]
@malcolmholmes @sh0rez In the end, I want to deduplicate information as much as possible. Both the directory tree where I keep my environment as well as the various JSON nodes above the K8s resource contain information that is potentially part of the resource again.

Assume for example I have two environments, sandbox and production, in the respective directories. Now I also want to have all resources include that name in the resources as a suffix, to avoid conflicts. (A little contrived, because this specific info would be in the environment metadata, I know). If I want to rename the environment, I have to rename the folder _and_ change the contents of the files.

This is not super important, neither the JSON part nor the folder part. It's unlikely to produce a lot of work in most situations, IMHO. Still for completeness sake I wanted to raise it.

**Comment by sh0rez** [comment]
So, for this specific example you can use `tk.env.metadata.name` which includes the relative path from project root to the environments directory.

Furthemore, the directory structure is not required to resemble the cluster architecture. Tanka has no assumptions on how to layout the project, so the user has full flexibility.
