### ISSUE TITLE
Support extVars

### ISSUE THREAD

**Issue by Grannath** [grafana/tanka#168]
Another use case I've found hard to support are dynamic environments. In case anyone here is using GitLab, you might know what I mean. They have a feature called review apps. For every merge request, a new environment is created with a name based on the branch name.

Support for such things relies on being able to pass in parameters at deploy time, that were not known when writing the environment files.

Possible ways to do this, that I can think of right now:
1. Allow adhoc patches. This could be in jsonnet format, or something similar to the Helm `--set` syntax. (powerful, but complex)
2. Allow key value pairs that will be available in the `tk` namespace. (less powerful, but easy, and values can be anticipated and checked in the jsonnet files)

What do you think, do you have similar usecases? This could also allow for integration with secret management using a bit of scripting to inject the values at deploy time. Or automatically including output from Terraform. Really, all kinds of integrations become possible.

**Comment by sh0rez** [comment]
So, you basically want to inject data from the outside at runtime? Jsonnet already has the concept of `extVars`, which allow to do that: pass external data from the command line. Those are accessible using `std.extVar('key')`.

Tanka does not expose this functionality of the compiler yet, but we can easily add it. Could look like this:

```
$ tk show environments/default -e=key=value
```

This could even support passing snippets of Jsonnet code.

Would that work for you?

**Comment by malcolmholmes** [comment]
Or you could just import a json file, and have your build process write data to it before invoking Tanka. That way, no change required to Tanka.

**Comment by Grannath** [comment]
@sh0rez Thanks, I'm not well versed in jsonnet itself yet. That looks exactly like what I want, just didn't see it in the tk options. Sorry I'm so bad in go, or I would just try to create a PR for this. Sounds pretty easy.

@malcolmholmes Sure, or template the files with e.g. envsubst. But it's exactly that kind of hacking that I want to avoid. It's just too fragile and complicated, IMHO.

**Comment by sh0rez** [comment]
Generating json that is imported afterwards is a perfectly valid solution.

Could you please share some more details on what you are trying to achieve? Which tools, how you want to couple them, etc

**Comment by Grannath** [comment]
Let's see. Assume I have an AWS SQS queue I want to connect to. I create one per environment, and I want to create new ones dynamically. I store the ARN for the queue in some variable `$SQS_QUEUE_ARN` in my CI script.

The easiest way I see, both to write and to maintain it, is something like `tk apply -e sqsArn=$SQS_QUEUE_ARN` [...]. This is how I do it if I want to use Helm.

The alternative you proposed was importing a file. So my CI becomes something like:
```bash
cat << EOF >> externalValues.json
{
  "sqsArn": "$SQS_QUEUE_ARN",
  [...]
}
EOF
tk apply [...]
```
Here the filename is defined somewhere in the jsonnet files. This is a) much harder to read and write, and b) needs synching between the jsonnet files and the CI for the file location (if I understood correctly).

Since you mentioned that jsonnet already supports extVals, I think exposing them to the user is a reasonable move. Importing files I think also has it's use cases. But for single values like this I think it just makes it more difficult.

**Comment by prune998** [comment]
I also used the `--ext-str` on the commandline, which is a variation. I used it like : 
```
--ext-str commit=$(git describe  --always --tags --long --abbrev=8)
```

This is explained in the section **External variables** of the doc https://jsonnet.org/learning/tutorial.html

My use-case is that I need to split a full application deployment in scenarios, like 1) deploy everything in a single namespace or 2) deploy half of it in two different namespaces.
My thinking was to create a lib with the code to deploy each micro-service, then use "environments" to code each scenario.
As I'm using K8s external load-balancers, I need my CI to create them, grab the public IP, then use tanka to generate the YAML with the right IP.
I was thinking passing it on the commandline, like I used to do it with jsonnet...

**Comment by prune998** [comment]
BRW, I was also using `--ext-code-file env=dev.jsonnet` to load the specifics of the env from a file. In this case it was inside the "jsonnet" bundle, so it could just be in the `main.jsonnet` from the `dev` env... but this is the option you should implement in tanka to support external file upload.

**Comment by sh0rez** [comment]
@Grannath 
> needs synching between the jsonnet files and the CI for the file location (if I understood correctly).

That's true, but it also applies to `tk apply -e`, because you access the passed value using `std.extVar("key")`  and this key is passed on the CLI ... so those need to be linked as well.

**Comment by Grannath** [comment]
OK, this is getting out of hands. My point is not "it's impossible to do xyz". I can always get it working. In fact, I can get stuff deployed without tanka. The point is to make it as easy as possible for as many users as possible.

First, I believe the group of people or projects that need to pass one or two values only is much larger than the one that needs to pass a file that can be read by jsonnet directly. So to cater to the largest possible user group, tanka should allow me to pass in values more easily than putting them all into a file first in a specific location and format (which is known to be hard to create by hand, that's why there is yaml, jsonnet, ...). It saves copy pasting the setup code in every project, and it lowers coupling (requiring a value is application logic, requiring a file location is an implementation detail).

The second reason is consistency. Helm, e.g., knows `--set`, `--set-file` and `--set-string`. jsonnet itself knows `--ext-var`, `--ext-var-file`, `--ext-code`, `--ext-code-file`. People are used to this, so tanka should not make them jump through extra hoops to get the same result.

Because tanka is a wrapper around jsonnet, in a way, I would propose to add the relevant options from jsonnet to tanka as well. That would be `--ext-var[-file]`, `--ext-code[-file]`. Maybe also the tla args, I don't quite understand what they do yet.

**Comment by sh0rez** [comment]
> Because tanka is a wrapper around jsonnet, in a way, I would propose to add the relevant options from jsonnet to tanka as well. That would be --ext-var[-file], --ext-code[-file]. Maybe also the tla args, I don't quite understand what they do yet.

Totally on this with you! The lack of `extVar` support is not intended, we can and should add this. Also for use cases like #171 where passing data from the outer environment is required.

Furthermore, I guess we can drop `extVar` in favor of `extCode`, because afaict, `extVar` creates strings, while `extCode` can create all Jsonnet types, including strings.

Do we really need `-file` flags? As long as shells are used, folks can still use the `$(cat file)` syntax ... and in CI, etc it might be even easier to pass inline anyways

**Comment by Grannath** [comment]
@sh0rez I do not have any experience with the jsonnet cli. I can imagine the extCode being interesting to calculate one ext value from another. But I never tried this. I also never used the file versions myself, but I see it in basically every tool. So I guess some people have a use for it.

I have not checked the code yet. If it's easy, I would add all that jsonnet has. If not, let's start with the more important ones. See if anyone misses the other ones.

**Comment by seh** [comment]
Here a few patches for _kubecfg_ that touch on these same problems:
- bitnami/kubecfg#265
- bitnami/kubecfg#266

Following on from those: google/go-jsonnet#329.
