### ISSUE TITLE
Release instructions install from sh0rez/tanka instead of grafana/tanka

### ISSUE THREAD

**Issue by chancez** [grafana/tanka#169]
The instructions for installing tanka in https://github.com/grafana/tanka/releases reference the old location of Tanka at https://github.com/sh0rez/tanka instead of https://github.com/grafana/tanka

**Comment by sh0rez** [comment]
This can be fixed by modifying https://github.com/grafana/tanka/blob/master/.drone/release-note.md and running `make drone` afterwards

**Comment by chancez** [comment]
Maybe if I find myself with some extra time. I'm on some deadlines to get Loki working :)
