### ISSUE TITLE
Erroneous messaging when api not available

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#172]
I just tried to apply to a local k3d cluster. The endpoint was down. Saw this:

```
Unable to connect to the server: EOF
Warning: There are no differences. Your apply may not do anything at all.
Unable to connect to the server: EOF
obtaining versions: exit status 1
```
This is unhelpful, as there *were* differences. Can we suppress the warning if the API server is not there?

**Comment by sh0rez** [comment]
Sorry, I can't reproduce this. With a stopped `k3s` server, I get the following (expected error) from kubectl:

```
$ tk apply environments/default
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
connecting to Kubernetes: obtaining versions: exit status 1
```
