### ISSUE TITLE
Bring back `import "foo.yaml"`

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#177]
We had to disable this in #176, because of #135.

Bringing this back requires upstream changes to Jsonnet: https://github.com/grafana/tanka/issues/135#issuecomment-571228938

**Comment by sh0rez** [comment]
@sbarzowski do you see any chance a change to go-jsonnet could make that possible? Otherwise I will close this issue

**Comment by sbarzowski** [comment]
Not anytime soon. There's a lot of lower hanging fruit. For now we'll need to live with `parseYaml(importstr 'foo.yaml')`. And if/when we introduce upstream support it will probably require little or no change here.

I've opened an issue on Jsonnet side to track this idea (https://github.com/google/jsonnet/issues/878). We can close it here, I think.

**Comment by sh0rez** [comment]
Sounds good to me! Let me know if I can help!
