### ISSUE TITLE
Setting up DiffStrategy should take also client version into consideration

### ISSUE THREAD

**Issue by cezkuj** [grafana/tanka#187]
I've used `tanka` with client <1.13 and server >= 1.13. DiffStrategy (https://github.com/grafana/tanka/blame/master/pkg/kubernetes/kubernetes.go#L51) was set to native and failed due to lack of kubectl diff on client side. Seems like it would be enough to extend condition in given file - would be happy to create PR with such change.

**Comment by sh0rez** [comment]
I assumed `kubectl` needed to be at least the cluster version ... but apparently one minor version less is supported as well: https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl

Taking this into consideration, yes, I'd be happy with you doing this change. Adding the same check for the clientVersion as well should be sufficient.

**Comment by sh0rez** [comment]
I think this should also print a warning, to let users know that their cluster supports the by far better diff mode and they just need to update their client.

**Comment by cezkuj** [comment]
I've tested it briefly and I'm not sure about printing a warning, it seems a bit redundant, as most of people using older clients have some reasoning behind it and won't upgrade just because of warning.
@sh0rez do you have something additional in mind that could make it worth it?
