### ISSUE TITLE
tk apply shows a pointer address before applying, instead of showing the diff result 

### ISSUE THREAD

**Issue by davidovich** [grafana/tanka#199]
```
root@5943b012b8d2:/workspaces/dockerandkubernetes101/figlet# tk apply deploy/figlet/configmap
0xc002ad7460
Applying to namespace 'default' of cluster 'docker-desktop' at 'https://kubernetes.docker.internal:6443' using context 'docker-desktop'.
```

Note: `0xc002ad7460`

This is caused by using [fmt.Print(diff)](https://github.com/grafana/tanka/blob/3022dabd3291f612a55634bc7c27c033cef7daec/pkg/tanka/workflow.go#L37) instead of `fmt.Print(*diff)` because `diff` is a `*string`

PR coming.

**Comment by sh0rez** [comment]
Fixed in #200
