### ISSUE TITLE
server err: cannot convert int64 to string

### ISSUE THREAD

**Issue by mplzik** [grafana/tanka#205]
Invoking `tk diff` sometimes results in a message like:
```
$ tk diff environments/abc/def
Error from server: cannot convert int64 to string
No differences.
```

This is slightly confusing, not giving a clear message about what exactly has happened. Is there any way to make it more clear/get rid of it?

**Comment by sh0rez** [comment]
Reopening as there is another error from the server, need to figure out why

**Comment by mplzik** [comment]
So, a quick googling found gave a suggestion -- a configmap entry that's rendered as a number, although configmaps accepts string values as keys: https://medium.com/@ismailyenigul/kubernetes-configmap-and-cannot-convert-int64-to-string-error-ebf48fa1cd28 . Might be worth looking at the generated configmaps.

**Comment by sh0rez** [comment]
So, we did solve this problem, it was not related to Tanka.

The respective kubectl issue is here: https://github.com/kubernetes/kubernetes/issues/65112. Basically you need to check for any values (env var, service name, configMap values) that use `type int`. These should be quoted to render as `type string` instead.

Admittedly the error message of kubectl is pretty useless, but nothing we can change.
