### ISSUE TITLE
Feature: export generated resources as files

### ISSUE THREAD

**Issue by olegmayko** [grafana/tanka#206]
Similar to Kube-prometheus, it would be nice if tanka could generate manifest files, which can be deployed in different way e.g. using gitops approach.

**Comment by sh0rez** [comment]
Hi! This is a cool feature we should definitely do!

The `--dangerous-allow-redirect` flag is meant as a protection to stop people from naively piping the `tk show` show output into `kubectl`, without being aware that they now need to handle choosing the correct context, etc themselves.  
That being said, extending this flag is probably not the right place to implement this.

Instead, I would propose to add a new command (`tk export`), that would take a directory and render out each Kubernetes object as a single `.yaml` file, properly named (`apiversion-kind-name.yaml`.

WDYT?

/cc @metalmatze

**Comment by olegmayko** [comment]
Awesome. thanks! It works.
