### ISSUE TITLE
Edge cases while using vendor per environment approach.

### ISSUE THREAD

**Issue by olegmayko** [grafana/tanka#207]
It's related to #198. Two cases I've noticed when this feature doesn't work/search correctly: 
1. I've added jsonnetfile.json and tkrc.yaml into environments/minikube folder. I excluded from it importing ksonnet/ksonnet.beta.4/k.libsonnet as it's already in *global* vendor. But it failed
 tk apply -v environments/minikube

> evaluating jsonnet: RUNTIME ERROR: couldn't open import "ksonnet/ksonnet.beta.4/k.libsonnet": no match locally or in the Jsonnet library paths
>        /Users/oleg/git/k8s-services/tanka/environments/minikube/vendor/ksm/kube-state-metrics/kube-state-metrics.libsonnet:1:11-54 thunk <k> from <$>
>       /Users/oleg/git/k8s-services/tanka/environments/minikube/vendor/ksm/kube-state-metrics/kube-state-metrics.libsonnet:33:25-26
>       /Users/oleg/git/k8s-services/tanka/environments/minikube/vendor/ksm/kube-state-metrics/kube-state-metrics.libsonnet:142:5-16
>       During manifestation

I had to add back ksonnet dependency into jsonnetfile.json. 

2. I've added libsonnet to lib folder (which is created by tk init) and I try to call it
> local g = import 'generic.libsonnet'; 
but 
>tk apply -v environments/minikube
>evaluating jsonnet: RUNTIME ERROR: couldn't open import "generic.libsonnet": no match >locally or in the Jsonnet library paths

However, if add dir prefix it works. 

> local g = import 'lib/generic.libsonnet';

Let me know if you need additional information.

**Comment by sh0rez** [comment]
`tkrc.yaml` **NEVER** belongs into an environment, but into the root of your project (where `vendor/`, `lib/` and `jsonnetfile.json` are located).

Telling from what you said above, you put it into `environments/...`?

https://tanka.dev/libraries/overriding#create-tkrcyaml and https://tanka.dev/directory-structure#root-and-base explain why.

**Comment by olegmayko** [comment]
sorry, my bad. it works.
