### ISSUE TITLE
tk apply diff is not colored anymore

### ISSUE THREAD

**Issue by pracucci** [grafana/tanka#209]
I've just upgraded to tanka `master` and noticed that the diff displayed by `tk apply` is not colored anymore. The previous version I was running was `0.5` and the output was colored there.

**Comment by pstibrany** [comment]
I'd prefer an option (ideally one that can be set via env. variable, so that I can turn it off globally) for this. Tanka's built-in coloring always messed up my terminal.

**Comment by pracucci** [comment]
> Tanka's built-in coloring always messed up my terminal.

In my experience `tk diff` is messing up with colors due to the paging, but not `tk apply`.

**Comment by rfratto** [comment]
> In my experience tk diff is messing up with colors due to the paging, but not tk apply.

FYI, #210 should fix the problems with colors in `tk diff`.
