### ISSUE TITLE
Receiving cryptic error when applying

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tanka#211]
On an internal infrastructure repo I'm receiving a cryptic error followed by a "no diffs" prompt.

```
$ tk --version
tk version 839649e
$ tk apply environments/jaeger/ops-tools1-######.jaeger/
0xc00b385550
Applying to namespace 'jaeger' of cluster 'gke_ops-tools#################' at 'https://xx.xx.xx.xx' using context 'ops-tools1-######'.
Please type 'yes' to confirm: ^C
```

v0.7.0 shows the expected diff.

**Comment by sh0rez** [comment]
This is the pointer of the diff, instead of it's contents. Already fixed in https://github.com/grafana/tanka/pull/200
