### ISSUE TITLE
Docker image is not self-contained

### ISSUE THREAD

**Issue by olegmayko** [grafana/tanka#218]
Hi, 
Sometimes the host systems especially in case of ci/cd don't contain kubectl binary. It leads to 
> connecting to Kubernetes: creating client: finding usable context: exec: "kubectl": executable file not found in $PATH

Do you think this can be added to off. image or prefer to keep it minimal?

**Comment by sh0rez** [comment]
Hey, looks like you are the first person to actually try that image, apparently it's unusable.

Of course we should add things:

- kubectl (how to get it best?)
- colordiff
- less

**Comment by olegmayko** [comment]
> kubectl (how to get it best?) 

either via FROM: bitnami/kubectl 
or as it's suggested on official doc https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-with-curl-on-linux 
what do you think?
