### ISSUE TITLE
[documentation][improvement] Environment not found

### ISSUE THREAD

**Issue by t0xicCode** [grafana/tanka#222]
It would be useful to improve the documentation regarding tanka environments, highlighting the lack of assumptions: environments are simply folders, under the project root, that contain a `main.jsonnet`. They are not required to be under the `environments/` top folder.

As well, the error messages that are outputted when a given environment is not found could be improved, for instance using plain language description in addition to the error message, along with potential solutions.

Original issue:
> Currently, tanka commands such as `tk show` and `tk env` (likely others too) require that the command be issued from the root of the project. Current behaviour assumes that the current folder is always the project root, so running any of those commands results in an error trying to load the environment (often: `loading environment: resolving jpath: open [cwd]/environments/default: no such file or directory`).
> 
> It would be nice if tanka supported execution from any subdirectory of a project. Tanka could walk up the filesystem, starting at the current directory, until a project is found. This way the current behaviour is still maintained, but usability is improved as users don't need to remember to go up to the project root before executing a command.

**Comment by sh0rez** [comment]
Hi! Tanka does that exactly that :D

The argument commands like `show`, `diff` or `apply` take is the relative directory from the directory to your environment. Example:

| dir you are in | argument you give |
|-|-|
|project root|`environments/default`|
|`environments`|`default`|
|`environments/default`|`.`|

Hope that helps :D

**Comment by malcolmholmes** [comment]
and it then walks back up the tree looking for `jsonnetfile.json` to identify the root of the project.

**Comment by t0xicCode** [comment]
Ah, so it's not dynamic. Has it been documented? I haven't been able to find it (TBF, I only started using tanka today). I've been issuing commands such as `tk env set environments/default` from within `[projectRoot]/environments/default` and getting error messages, with no documentation or potential solutions.

Is there a want to make the path-resolution dynamic? I think that it would improve consistency, and may even open the door to simplify some commands. For instance, if a command only ever operates on environments, why specify "environments" in the path? Unless there's explicit support for naming the folder something else, typing it seems redundant. The command would know to prepend `environments/` to the given name.

Something like this.

dir you are in | argument you give|where you operate
--------------|--------------------|-------------------
project root | `default`|`environments/default`
`environments` | `default`|`environments/default`
`environments/default` | `default`|`environments/default`
`environments/default`|`.`|`environments/default`
`environments/default`|`other`|`environments/other`

It would separate the concept and locator of an environment from its actual location.

**Comment by sh0rez** [comment]
For Tanka, an environment is a folder with a main.jsonnet in it. That's it. No more assumptions.

Having the environments folder is really only a convention, nothing Tanka is opinionated about. If it does not fit your business, use another directory structure.

That being said, I don't think we can remove the environments/ bit from the path.
Another reason not to do it is that bash can autocomplete you the directory, which is important in terms of usability.

**Comment by t0xicCode** [comment]
> For Tanka, an environment is a folder with a main.jsonnet in it. That's it. No more assumptions.

👍  That's useful information! I was assuming, based on past experiences, that tanka was more opinionated.

> That being said, I don't think we can remove the environments/ bit from the path.

Which makes total sense if tanka doesn't expect or require environments to live in an `environments/` folder.

> Another reason not to do it is that bash can autocomplete you the directory, which is important in terms of usability.

Bash-completion could be done through other means, so that wouldn't be an explicit loss of usability. But given the permissive behaviour of tanka, it's totally fine to leave the `environments/` bits in.

I would move to update this ticket to improve documentation regarding what environments are (and the permissiveness of their location within a project), and potentially improve the error messages when a `main.jsonnet` is not found at the given location.
