### ISSUE TITLE
Apply CRDs in advance of any CRD-dependant resources.

### ISSUE THREAD

**Issue by mplzik** [grafana/tanka#226]
Currently, Custom Resource Definitions (CRDs) are not being given any kind of special treatment, which can easily result in CRD-defined resources being applied before the actual CRD is present in the cluster, making kubectl fail.

Tanka already implements special handling for namespaces, which get applied before anything else; a similar approach might work for CRDs as well.

**Comment by sh0rez** [comment]
Yes, and while we are on it, we should extend that hacky namespace sorting into a proper object sort engine, to do a multi-staged apply.

We should have clearly defined rules somewhere in the code that group objects together and then run `kubectl apply` on each of the resulting groups in series.

**Comment by sh0rez** [comment]
What I can think of right now:

1. Namespaces always first
2. CRD's right after that
3. Everything else

Any more sorting that needs to happen? I guess Kubernetes deals with most other object inter-dependencies pretty well?

**Comment by mplzik** [comment]
Since the implementation wasn't that difficult, I implemented a draft PR for this: https://github.com/grafana/tanka/pull/227

**Comment by mplzik** [comment]
W.r.t. object orders. I guess that in most cases, Kubernetes will eventually (as in "might fail few times, but will succeed in the end) handle things correctly; there are only few cases of a real breakage. The PR I sent does some extra work to ensure some sane rules (e.g. `PodSecurityPolicy` objects get applied before anything that creates pods, and so are `ConfigMap`s and `Secret`s). If that's pre-mature, I'll be happy to trim the list just to the cases we know are causing trouble.

**Comment by steeling** [comment]
>[...] which can easily result in CRD-defined resources being applied before the actual CRD is present in the cluster, making kubectl fail.

Doesn't it always fail, since tk will first try to `diff` before `apply`? I don't mind having to run `tk apply` twice to get the resource definitions out, but I have to actually edit my configs when turning up a new cluster to comment out any usage of CRD's


Additinally, it would be nice to be able to integrate our tk configs with cert-manager, which currently requires the flag `--validate=false` on apply https://cert-manager.io/docs/installation/kubernetes/

**Comment by sh0rez** [comment]
> Additinally, it would be nice to be able to integrate our tk configs with cert-manager, which currently requires the flag --validate=false on apply https://cert-manager.io/docs/installation/kubernetes/

Won't `tk apply --validate=false` work?

---

> Doesn't it always fail, since tk will first try to diff before apply? I don't mind having to run tk apply twice to get the resource definitions out, but I have to actually edit my configs when turning up a new cluster to comment out any usage of CRD's

Actually, apply should work even if diff fails. I know this is not the case right now (we don't handle that error properly), but it is something we could easily do.

**Comment by mplzik** [comment]
@steeling diffing indeed fails. We're currently trying to figure out a reasonable way to work around this issue, but unfortunately it's more complex than other similar code (e.g. filtering out the non-existent namespaces, which is already implemented in Tanka). One of the goals of this PR is to make Tanka work with more complex deployments, including cert-manager (which is also what we are trying to make work with this PR).

W.r.t. `--validate=false`, as @sh0rez already said, this is a supported option in Tanka. Note that the need for this flag is caused by cert-manager using Kubernetes 1.15 features -- see https://github.com/jetstack/cert-manager/issues/2441 for more information. There's not too much that can be done from Tanka's side.

**Comment by sh0rez** [comment]
I think we did implement this in #244. Can you confirm and close @mplzik?

**Comment by mplzik** [comment]
Resource re-ordering has been implemented; but there's still some work on the diffing part to make diffs behave correctly; that's the reason why I left this issue open for now.

**Comment by sh0rez** [comment]
The pending diff work is tracked by https://github.com/grafana/tanka/issues/246. Closing this one
