### ISSUE TITLE
Secret Management

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#230]
Right now, Tanka does not handle secrets itself, mostly because there are other tools on the ecosystem available that fill the gap.

However, this is unobvious to many users, so it seems worth collecting good options and adding them to the docs.

Incomplete list of tools:
- [`git-crypt`](https://github.com/AGWA/git-crypt)
- Mozilla SOPS: https://github.com/mozilla/sops
- Sealed secrets: https://github.com/bitnami-labs/sealed-secrets

In the long run it might still be desirable to integrate with secret tooling more tightly, however this might look like. This is a topic open for discussion, as we should make sure we invest our resources on this properly and don't invent the tool nr. 15 nobody needs.

**Comment by streetmapp** [comment]
It would be great if tanka was able to integrate with any of these tools. I'm biased towards `sops` for sure as that's what's currently being used. But anything that can fit in this need would be awesome.

**Comment by ghostsquad** [comment]
I'm happy to share some code I have for using SealedSecrets.

this script using KubeSeal to seal a secret based on a temporary secret that is generated and then destroyed. (The source of truth for us is to use AWS Secrets Manager, instead of say keeping files locally and gitignoring them).
https://gist.github.com/ghostsquad/e305a36c37519df54d9c42c3dfb9e673?ts=4

The secret looks like this:

```
# note that this is NOT rendered during deployment time
# instead its used during generating the sealed secret
function(
    NAME_PREFIX,
    STRING_DATA, // tla-code
    SEALED_SECRET_SCOPE,
) {
    local secret = self,

    local dataMD5 = std.md5(std.manifestJsonEx(STRING_DATA, "")),

    apiVersion:"v1",
    kind: "Secret",
    metadata: {
        annotations: {
            "company.com/data-md5": dataMD5,
            ["sealedsecrets.bitnami.com/%s" % [SEALED_SECRET_SCOPE]]: "true"
        },
        name: "%s-%s" % [NAME_PREFIX, std.substr(dataMD5, 0, 12)],
    },
    stringData: STRING_DATA,
}
```

I really like SealedSecrets, since there's no private key or password that's needed locally to encrypt. You must have access to the K8s cluster you are deploying to.

**Comment by malcolmholmes** [comment]
Keeping secrets inside a Tanka config requires those secrets to be available to every engineer. Yes, we can encrypt them with something like git-crypt, but rotating them when necessary becomes hard.

We've found that it is best to keep secrets outside of Tanka. We've a fork of [Pentagon](https://github.com/grafana/pentagon) that syncs secrets from Vault into Kubernetes secrets. In Tanka we define that mapping (vault secret->kubernetes secret), but we don't define the actual secret. This keeps the secret off engineer's laptops, making it easier to rotate, secure and manage.

**Comment by sh0rez** [comment]
Closing this ticket, as it is not really an issue Tanka needs to solve.

As @malcolmholmes explained above, our own solution involves HashiCorp Vault and Pentagon, which we consider more powerful than Tanka support for Vault.

For simpler use-cases, the following static tools are certainly an option as well:
- [`git-crypt`](https://github.com/AGWA/git-crypt)
- Mozilla SOPS: https://github.com/mozilla/sops
- Sealed secrets: https://github.com/bitnami-labs/sealed-secrets

**Comment by phongngthanh** [comment]
I would love to see some form of integration with sops. It's already possible to import a random yaml/json file (https://tanka.dev/jsonnet/injecting-values#json-files), so an sops integration in my mind would do the same thing but with an sops encrypted file.
