### ISSUE TITLE
Jsonnet lazy evaluation when specifying a target

### ISSUE THREAD

**Issue by steeling** [grafana/tanka#236]
This will probably get deprioritized, and is probably difficult to implement given the separation between jsonnet and tanka, but it would be nice to not evaluate errors on objects that are ignored when specifying a target, ie:

{
  a: {
    myerror: error 'this could be avoided',
  },
  b: {
     kind: 'Deployment',
     name: 'b',
     ....
   },
}

tanka show <file> -t deployment/b

As long as the object 'b' never references anything that references a.myerror.

**Comment by malcolmholmes** [comment]
@steeling you are correct that, while nice, it is going to be extremely hard to do. We have Jsonnet source, and then we have JSON output which is filtered for Kubernetes resources. The target feature happens at this late stage. We cannot easily connect a line of source code to a specific output, meaning we require the whole Jsonnet to render, even if we only pick one element from it.

My only suggestion is to use source control to go back to a known good state and apply a single resource from there. Not a great suggestion, but it's what I have.

**Comment by sh0rez** [comment]
How much I'd love to have this, I fear @malcolmholmes point makes this too hard: At no point Tanka is part of the actual Jsonnet evaluation .. this is the realm of the compiler. Whatever Tanka does can only be *before* or *after* that ... we can't influence properties during the actual evaluation.

Targets are implemented late-stage. They are nothing more sophisticated than a regex filter on the flattened JSON output of the compiler.

Unless I miss something here (/cc @sbarzowski), I don't think we can do a lot about this.

---

The only workaround I can think of is clever use of `extVars`:

```jsonnet
// main.jsonnet
local target = std.extVar("target");
local app = {
  grafana: { /* ... */ },
  prometheus: {
    api: error "not implemented",
  },
};

if target != "" then app[target] else app
```

When invoked as `tk show environments/default --extVar=target=grafana`, it would still evaluate.
This of course is less than ideal, but with some careful design it might ease the described pain.

**Comment by sbarzowski** [comment]
I don't know what `tk show` does under the hood, so I don't know if the following is possible. Perhaps Tanka could request the object `b` rather than the whole thing from a Jsonnet file. You could evaluate a Jsonnet snippet - something like `(import "file_from_which_to_get_stuff.jsonnet").b`.

**Comment by sh0rez** [comment]
@sbarzowski that's not really an option. The structure of the evaluated Jsonnet is not clearly defined. It may be a big object, array, nested, whatever. The only thing we know is that somewhere in there valid Kubernetes resources live. Tanka searches for them: https://github.com/grafana/tanka/blob/master/pkg/kubernetes/reconcile.go

Because we don't know where something will come from, targets is implemented late-stage, on the flattened list. From what I can tell above properties don't allow us leveraging Jsonnet lazy eval .... tho it would be surely awesome as it might also radically lower evaluation speed.

**Comment by sbarzowski** [comment]
Hmmm... perhaps if you implemented the `Reconcile` in Jsonnet that would be possible. I mean it would need to be shallowly evaluated to find the Kubernetes resources, but the fields of objects which look like Kubernetes manifests wouldn't be (beyond what is needed to check that they are in fact Kubernetes manifests). It would probably add a bit of overhead when evaluating the whole thing. The main problem with doing this is that you use regexps there and we don't have them (yet) in Jsonnet.

**Comment by sh0rez** [comment]
> implemented the Reconcile in Jsonnet that would be possible

Certainly worth a try, altough I have some concerns:
- it would mix two stages of Tanka's lifecycle: evaluation and processing, which are currently kept separate two possibly allow other languages than Jsonnet
- Is it totally safe to wrap the users code in more Jsonnet? I imagine it a nightmare debugging this as a newcomer when things go wrong and your code includes stack traces from files that are not even on disk

> The main problem with doing this is that you use regexps there and we don't have them (yet) in Jsonnet.

Ksonnet defined a nativeFunc for that which we inherited: https://tanka.dev/jsonnet/native#regexmatch. This should have us covered.
