### ISSUE TITLE
Tanka should label manifests it manages.

### ISSUE THREAD

**Issue by captncraig** [grafana/tanka#249]
Labelling resources has come up before in #88 and others, but regardless of pruning strategies, I would like to see tanka adding appropriate metadata to resources it manages in order to ease operations. This is typical for most tools in the space. 

I would like to see the following added:

**labels:**

- `app.kubernetes.io/managed-by: tanka` - from [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)
- `tanka.dev/environment:$ENV_NAME` - make finding objects by environment name easier, and make analytics / pruning easier. 

**annotations:**

- (maybe) `tanka.dev/version` - version of tanka tool would be interesting to have. Ideally all deploys are done by a CD tool so there wouldn't be flapping or contention on this. It could also be an annoyance (or a signal to upgrage) when running locally. 
- (maybe) `tanka.dev/hash` - a simple hash of all manifests after parsing. Useful for a basic "version" of an environment or identifying unpruned resources.

Those annotations would be really annoying if they polluted the diff on every run. If they can be hidden from the diff and injected at the last minute they may be useful, but possibly not worth the trouble.

An argument may be made that tanka is made to be a general purpose config management tool, not neccessarily a lifecycle management tool and should therefore keep its hands off of resources it manages. But I would also argue that this feature is required to make some of our other lifecycle management features work, and is too important to be left up to conventions for environment authors. A flag to control them seems reasonable, but I would like to see it going from opt-in to opt-out within a short time span.

**Comment by sh0rez** [comment]
Implemented as part of #251
