### ISSUE TITLE
Add namespace to resources when exporting manifests file

### ISSUE THREAD

**Issue by primeroz** [grafana/tanka#269]
When exporting resources to manifest files with `tk export` it would be very useful to add the namespace, as specified in the `spec.json` to the namespaces resources.

I understand tanka used to handle namespaces for resources but was removed in favour of using kubectl to do that.

I suggest that , only for the export command, this is restored

### My use case
We use `flux` with a monorepo containing loads of resources in a lot of different namespaces ... with the current behavior of tanka i need to wrap the generated manifests in a kustomize so that i can add the namespace to the resources then re-render the manifests.

**Comment by captncraig** [comment]
I was literally about to file this exact issue. When building additional tooling that uses tk output, it would definitely be nice to have full namespaces in place. Yes, kubectl can kinda fill in the gaps when deploying to the cluster, but if you are doing anything else (like show or export) you need to look at the environment context to know the namespace.

One option that I have thinking about is simply requiring all namespaced resources to have namespaces defined, and fail if they don't. Its a strong-armed opinionated stance, but I for one am kinda ok with that.

Alternatively, in the Reconcile phase we could just insert the environment namespace anywhere it is absent. Tanka does already fetch the api-resources from the cluster, so it should be able to fairly confidently know what needs a namespace and what doesn't.

**Comment by captncraig** [comment]
I guess one problem with `show` and `export` is that they don't require a cluster or kubectl. So knowing which resources are namespaced could be problematic. Especially with CRDs.

**Comment by sh0rez** [comment]
> Tanka does already fetch the api-resources from the cluster, so it should be able to fairly confidently know what needs a namespace and what doesn't.

While Tanka *can* fetch the resources, it does not do it usually. Only the `diff` and `prune` actions do so, because they require that for their internals. 

Because `kubectl api-resources` is comparably slow, it will be a tradeoff:

```
tk show ...            0.79s user 0.09s system 171% cpu 0.510 total
kubectl api-resources  0.40s user 0.40s system  30% cpu 2.631 total
```

Furthemore, the point raised by @captncraig about `show` (and thus `export` being a static operation is probably a show stopper. 

@primeroz you mentioned on Slack that `kustomize` can be used as a workaround to add the namespace to our current artifact. Does it handle  non-namespaced objects,  and if so, in what way?

**Comment by captncraig** [comment]
I do really want this though. Our own environment tree is pretty sloppy about defining namespaces on things, and I wish it wasn't so. 

I've made a few one-off tools now to analyze different resources based on `tk show`, and I ran into a lot of issues with things not having namespaces where I had to go in and figure out they were assumed. 

One idea I had was a lint check. Either in tanka or manually, but something that can be run as a pr check or whatever. Generate all manifests and then query cluster resources, and make sure all manifests that should have namespaces do. Make it the environment author's job to make sure everything is explicit.

**Comment by primeroz** [comment]
@sh0rez yeah kustomize does handle the both namespaced and non-namespaced objects really well.

How does it do it exactly ? from my understanding kustomize just uses transformers with a predefined list of of resources / fields to patch and it supports adding extra resources or fields for non standard resources like CRD ... 
* https://github.com/kubernetes-sigs/kustomize/blob/7d852c7bab15a9fcaf223fd195182da62c347df5/plugin/builtin/namespacetransformer/NamespaceTransformer.go
* https://github.com/kubernetes-sigs/kustomize/blob/78abd4193aa5414204bf240dcb1542e81ade03b3/api/filters/namespace/namespace.go
* https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md 

So i don't think it is the most scalable way of doing it 

in terms of configuration is not too bad , i would just do something like 
```
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: blah

resources:
- resources/TankaExportedManifest1.yaml
- resources/TankaExportedManifest2.yaml
...
- resources/TankaExportedManifestn.yaml

```

**Comment by primeroz** [comment]
Is it worth to keep this case open ?

I really look forward this feature but not sure if there is any plan to implement it.

thanks
