### ISSUE TITLE
tanka should validate correct jb version before initialising

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#270]
`tk init` was failing for me. Upgrading to latest `jb` fixed this. Would be good if Tanka validated that `jb` was a sufficient version before proceeding, as error message is not helpful otherwise:

```
jb: error: failed to install packages: downloading: failed to create tmp dir: stat vendor/.tmp: no such file or directory
Installing k.libsonnet: exit status 1
```

**Comment by sh0rez** [comment]
I fail to reproduce, especially considering Tanka used to work before jb0.3 was released just fine, and we did no changes in that area recently.

Your issue probably lies with a broken jb or a bug in there.

Closing, feel free to reopen if this indeed needs our attention!
