### ISSUE TITLE
Discuss Potential Safety Features

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tanka#275]
Given that Tanka is used to manage critical infrastructure I think we should consider additional safety features to warn or stop users from making potential mistakes.  Creating this issue as a point of discussion.

Some examples of "unsafe" changes:
- Scaling a deployment/statefulset to 0
- Reducing memory limits by a very large %

Possible options when changes are present:
- Highlight the difference and require a second prompt to confirm the "unsafe" change
- Highlight the difference and require the command to be rerun with a special "unsafe" flag

**Comment by joe-elliott** [comment]
@sh0rez what do you think ? do we want this?

**Comment by sh0rez** [comment]
I think it's cool, but not a big priority to me at the moment (there are more urgent things)
