### ISSUE TITLE
tk eval: Requires `spec.json` even though it is not needed

### ISSUE THREAD

**Issue by gotjosh** [grafana/tanka#280]
Given a simple jsonnet file with no tanka specifics, tanka will fail to eval complaining that there is not `spec.json` in the directory specified. 

I imagine this is not expected behaviour and that check should be removed when using `eval`.

**Comment by sh0rez** [comment]
Yes, the `show`, `export` and `eval` operations should work without. This is really just a overly strict assumption in our code, and not required.

**Comment by mplzik** [comment]
Note that this is different mode of operation for tanka -- so far it's been used only for k8s deployments and all the subcommands were tailored to that. I think the straightforward way for fixing this would make `tk` basically a `jsonnet` interpreter with benefits (native functions compatible with tanka).
