### ISSUE TITLE
docker swarm

### ISSUE THREAD

**Issue by vlcinsky** [grafana/tanka#281]
Great tool and excellent concept. Unfortunately we do not use Kubernetes but **docker swarm**.

# Our attempt to manage docker swarm

I managed to generate configuration files (currently docker-compose.yml, planning to generate also secrets or configuration files). Tanka helped in reusing following tanka concepts:
- consider application configuration a software artefact, publish it as libsonnet library - one per application stack
- in library, separate the configurable and templating stuff
- use "namespaces" to allow management of multiple stacks at once
- environment directories
- `main.jsonnet` as assembly definition, reusing default config and extending/fine-tuning the configuration where necessary

We also expect `jb` installed libraries to be perfectly fitting whatever orchestration framework incl. docker swarm.

What we did not manage (yet):
- `spec.json` to define target deployment environment (we could use env file with `DOCKER_HOST` and similar files, but did not arrive there yet)
- single tool to manage and apply the configuration - so far we use simple tooling to drive `jsonnet` binary generating config files which we then apply using `docker stack deploy --with-registry-auth -c docker-compose.yml stack_name`

# Searching for `tanka` like tool for docker swarm
I have found that in regards to configurability and flexibility is tanka much better than solutions like [docker-app](https://github.com/docker/app).

For that reason we are searching for tanka-like tool:
- tanka extension
- tanka clone dedicated to docker swarm
- other tool sharing concepts of tanks

Any ideas or hints?

**Comment by malcolmholmes** [comment]
Tanka has been deliberately made structured so that it can be consumed as a library. See https://github.com/malcolmholmes/grizzly. It follows the same show/diff/apply model, using jsonnet, but the end system is a Grafana install. You could possibly make an equivalent of Tanka (in Go) that reuses much of the stuff in common (parsing spec.json, jsonnet interaction, CLI stuff) and just implements the docker swarm specific stuff (diff, apply, etc).

We've certainly thought of the possibility of an ecosystem of jsonnet based tools. We don't use Docker Swarm ourselves, but it could be an interesting tool none-the-less.

**Comment by sh0rez** [comment]
While the approach @malcolmholmes would work as a last resort, there is probably something simpler for your use-case already available.

Please try out the `tk eval` command, which returns raw processed Jsonnet, without the Kubernetes specific transformations of Tanka applied. You will miss out some benefits Tanka adds with Kubernetes, however you still have full access to the Jsonnet configuration language, which seems your primary goal.

I'm not incredibly familiar with Docker Swarm, but you might be able to pipe that output directly into their apply mechanism, maybe using a Makefile.

**Comment by vlcinsky** [comment]
Using the `tk eval .` trick proposed by @sh0rez I managed to prototype swarm variant of tanka.

## Current features
- multiple stacks
- all `.env` configuration moved into jsonnet config files and rendered into `docker-compose.yml` files
- `secrets` and `configs` files generated and even shall manage their update (changing secret/config name using md5 hash of given file content to prevent clashes with already existing versions)
- written in Python, depending currently on `tanka`

## Subcommands implemented
Current command (designed as python package providing single command `sk`) allows to:
- `generate` to generate all stacks with all the files. Each stack gets independent directory named `_deploy/{stack_name}`.
- `fix` to modify secrets/configs names within `docker-compose.yml` to allow easy update of secret/config content without manually tracking previously registered versions.
- `clean` to clean the `_deploy` subdirectory

It shall be easy to implement:
- `apply` for all stack at once as well as a tool to do that just for single stack. Using `docker stack deploy`.

## Open issues (diff?)
I did not find a way to perform `diff` as I miss source of currently used configuration on swarm cluster (if anyone is aware of such information, I would appreciate it).

## Next actions: open source it
My plan is to share this as open source project within few weeks and provide here a link.

# How it works now
Implemented as single command `sk`:
```
$ sk
Subcommands:

  clean      Clean deployment directory `environment/{envname}/_deploy`
  fix        Fix secret and config names in docker-compose.yml in _deploy subdir
  generate   Generate docker swarm config files into `environment/{envname}/_deploy
```

Initial files defining set of stacks:

```shell
$ find .
.
./spec.json
./main.jsonnet
./configs
./configs/docker
./configs/docker/daemon.json
./configs/fluent-bit.conf
./configs/fluent-bit-parsers.conf
./secrets
./secrets/web.users
```

main.jsonnet:
```jsonnet
(import 'croads-dataview.libsonnet') +
(import 'croads_common.libsonnet') +
(import 'croads-datahub-masapi.libsonnet') +
(import 'croads_intp_reception.libsonnet') +
(import 'logs_common.libsonnet') +
(import 'croads-dataview.libsonnet') +
(import 'croads-produce-alerts.libsonnet') +
(import 'croads_traefik.libsonnet')
```

To generate resulting files:
```shell
$ sk generate

_deploy/croads_common/docker-compose.yml
_deploy/croads_datahub-masapi/docker-compose.yml
_deploy/croads_dataview/docker-compose.yml
_deploy/croads_intp_reception/docker-compose.yml
_deploy/croads_produce-alerts/docker-compose.yml
_deploy/croads_traefik/docker-compose.yml
_deploy/croads_traefik/secrets/web.users
_deploy/logs_common/configs/fluent-bit-parsers.conf
_deploy/logs_common/configs/fluent-bit.conf
_deploy/logs_common/docker-compose.yml
```

Resulting files:
```shell
$ find .
.
./spec.json
./main.jsonnet
./_deploy
./_deploy/croads_dataview
./_deploy/croads_dataview/docker-compose.yml
./_deploy/logs_common
./_deploy/logs_common/docker-compose.yml
./_deploy/logs_common/configs
./_deploy/logs_common/configs/fluent-bit.conf
./_deploy/logs_common/configs/fluent-bit-parsers.conf
./_deploy/croads_traefik
./_deploy/croads_traefik/docker-compose.yml
./_deploy/croads_traefik/secrets
./_deploy/croads_traefik/secrets/web.users
./_deploy/croads_common
./_deploy/croads_common/docker-compose.yml
./_deploy/croads_datahub-masapi
./_deploy/croads_datahub-masapi/docker-compose.yml
./_deploy/croads_intp_reception
./_deploy/croads_intp_reception/docker-compose.yml
./_deploy/croads_produce-alerts
./_deploy/croads_produce-alerts/docker-compose.yml
./configs
./configs/docker
./configs/docker/daemon.json
./configs/fluent-bit.conf
./configs/fluent-bit-parsers.conf
./secrets
./secrets/web.users
```

These files can be (currently) used by `docker stack deploy` command.

**Comment by vlcinsky** [comment]
I have published my attempt to **do like tanka, but for Swarm** on GitHub: https://github.com/vlcinsky/sanky

I already serves one of my project deployments, but is in very experimental stage anyway.
