### ISSUE TITLE
tab completion shows too much of the path.

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#29]
If I do `cd environments/` then press tab, I will see listed the directories inside `environments`.

If I do the same with `tk diff environments`, I will see `environments/default/blah`. It would be more helpful if it stripped off the `environments` portion, as I have already committed to that part of the path.

Also, it currently lists *all* of the paths that have a `main.jsonnet`. This is neat, but gives too many options. I would expect a sequence such as:

```
$ tk diff env<TAB>
$ tk diff environments/
$ tk diff environments/<TAB>
default hosted-grafana cortex loki cassandra blah
$ tk diff environments/cor<TAB>
$ tk diff environments/cortex/
$ tk diff environments/cortex/<TAB>
eu-west2.dev eu-west2.prod ops-tools1-us-east4.cortex blah
$ tk diff environments/cortex/ops<TAB>
$ tk diff environments/cortex/ops-tools1-us-east4.cortex
```
Here it has stopped completing, i.e. didn't put a `/` at the end of the dir, because there is a `main.jsonnet` file in that directory.

This would allow me to navigate swiftly to where I want to be without overfilling my screen.

**Comment by sh0rez** [comment]
Labeling this for https://hacktoberfest.com. The issue is not in Tankas code itself, but rather in the used library https://github.com/posener/complete and must be solved there. I would love to see somebody taking this!
