### ISSUE TITLE
tk show pager improvements

### ISSUE THREAD

**Issue by hamishforbes** [grafana/tanka#293]
There are a few things around paging in the `tk show` command that could be improved

### Don't use a pager when non-interactive
Currently output always goes through the pager even if `--dangerous-allow-redirect` is set and the command is being piped somewhere.

### Don't assume less is available
There's no way to disable paging, if you empty the `PAGER` env var tanka tries to use less whether it exists or not

### Don't assume less has flags it might not have
Related to #232, Tanka makes assumptions about the available flags on less. 
Which breaks busybox less at least

**Comment by ghostsquad** [comment]
`git` uses `--no-pager` option, which on top of the changes to the other assumptions would be good
