### ISSUE TITLE
Discourage piping

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#3]
It might sound appealing to users to do the following:
```
$ tk show | kubectl apply -f 
```
While this appears to be straightforward, it has a severe shortcoming: **It evades context handling**, by relying on a correctly set up `kubectl`. Usually, `tk` parses the output of `kubectl config view` and automatically selects the correct `context` based on the `spec.kubernetes.apiServer` field of `spec.json`.

This means in the worst case, a quick `tk show | kubectl apply -f` could result in the **disastrous** action of applying a config to the **wrong cluster**.

This will most likely have a severe impact on the running workloads and should be mitigated by design. Possible solutions:
* Use syntax highlighting on the output of `tk show`. The ANSI color chars will make piping impossible
* Make `tk show` emit to stderr. While the redirection is easy, it is counterintuitive and thus a step in the right direction
* Add `⚠️ Do not pipe the output of tk show. Use tk apply instead ⚠️` messages to the output.

While these should be the default, it is fair to add a `--allow-dangerous-piping` flag which will result in the current behaviour.

**Comment by rfratto** [comment]
you can also detect piping and abort:

test.go:

```
package main

import (
        "fmt"
        "os"
)

func main() {
        fi, _ := os.Stdout.Stat()

        if fi.Mode()&os.ModeCharDevice == 0 {
                fmt.Println("pipe")
        } else {
                fmt.Println("terminal")
        }
}
```

```
$ go run test.go 
terminal 
$ go run test.go | cat 
pipe 
```

**Comment by sh0rez** [comment]
Wouldn't this prevent all use in scripts as well?

**Comment by rfratto** [comment]
Not sure what you mean, this still works:

test.sh:
```
go run test.go
``` 

```
$ bash test.sh 
terminal 
$ bash test.sh | cat 
pipe
```
