### ISSUE TITLE
Tanka resource "status" checking

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#323]
Similar to how Spinnaker or ArgoCD "watches" resources to verify a stability.

This would extend `tk apply` possible with an option like `--health-watch`.

I was thinking this would be a perfect addition, because `tk` could also render/read a "workflow" to describe the order of manifests to deploy. All-in-one solution!

----

More Info:

https://spinnaker.io/guides/developer/extending/crd-extensions/
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesReplicaSetHandler.java?ts=4

https://argoproj.github.io/argo-cd/operator-manual/health/

**Comment by Duologic** [comment]
I'm not sure if I really understand what you mean (I have no real world experience with ArgoCD or Spinnaker).

Is it meant as a CD feature but implemented in Tanka? Up until now, we have seen Tanka as an "active component", it is either invoked by a user or other tools that facilitate automation. 

Can you elaborate a bit more on what this feature should do? Where does it sit in the process of getting manifests into kubernetes?

**Comment by ghostsquad** [comment]
Instead of just running the equivalent of `kubectl apply` this would also watch and wait for the status of the resource to become healthy/stable. If stability is not reached after a given amount of time, the command exits with a non-zero exit code to indicate failure.

This could be used as part of an `tk apply` such that the user can be confident that the resources deployed correctly. It can also be used in a CD pipeline for the same verification.

**Comment by ghostsquad** [comment]
This could be part of a different command too, in order to decouple the status watching from the apply of the resources.

If this is not a good fit for tanka, I'd want to implement this in a standalone CLI

**Comment by ghostsquad** [comment]
I think it probably makes sense to make this a standalone CLI. There's a library already that has many health checks: https://github.com/argoproj/gitops-engine/blob/master/pkg/health/health.go

My CLI is called `dicap` (Damage Indicator Capability) https://github.com/cakehappens/dicap

I think the a reasonable workflow might be 

```
tk show | dicap --input-format=yaml -
```

Let me know if there's a desire to collaborate on an integration like this

**Comment by Duologic** [comment]
I believe it might have a use case, however I mostly see that this gets covered by proper use of replicaSets, PDBs, RollingUpdates and decent minitoring.

**Comment by ghostsquad** [comment]
I'm talking about _at_ deployment time. If you mark the deployment a success, but it's not, then with monitoring, you later get a page that your deployment didn't actually complete.

This proposal in some ways _is_ that monitoring.

But, I think it's clear at this time that this feature request makes tanka responsible for _more_ than just rendering/diffing/applying manifests, which it should focus on.

**Comment by ghostsquad** [comment]
no official release yet, but I'm starting to look for feedback now for https://github.com/cakehappens/seaworthy - I have a simple MVP created.

I'm also advertising that it's `tanka ready`, though technically it's currently not. I plan to support such use cases as `tanka show . | seaworthy verify -f -` (and advertise that use case in the readme)

**Comment by Duologic** [comment]
`tk show` is not intended to pipe atm, you can use `tk export` and run it against the exported manifests. Would that be a viable solution?

**Comment by ghostsquad** [comment]
What's the reason for not being pipeable?

**Comment by Duologic** [comment]
It is designed for humans to inspect the output, it probably needs some thorough rethinking if we want to allow it. Maybe @sh0rez can give some more background.

**Comment by malcolmholmes** [comment]
The background is this. Tanka didnt put the namespace into all resources automatically, only the ones that code explicitly configures. This means that if we pipe tk show to a file, we get yaml that could be inconsistent. To use it correctly, you need to use kubectl with a namespace defined.

Now, I believe tanka handles namespaces differently now so the dangerous warning is less important. Not sure if there is still a good reason for it.

**Comment by sh0rez** [comment]
What both @malcolmholmes and @Duologic said is correct, but not the actual reason I added the flag back then.

Kubectl has contexts, which select the cluster it operates on. Tanka environments are very strict of their cluster, so you don't accidentally apply to the wrong one, which could have a very bad outcome. Tanka does this by setting the kubectl context via a flag when invoking it.

In the early days we've seen people piping the yaml to kubectl to apply it, or to a file, etc. We lose control over the context then. The flag is put in place to make people think.

Fun fact: the lack of `tk delete` for a long time caused a small incident at Grafana Labs because the yaml was piped - to a wrongly configured kubectl

It's totally fine to pipe the yaml, as long as the receiver takes care to apply it only where it belongs.

**Comment by ghostsquad** [comment]
Good thinking!!! I'll consider this as well to improve the usability of `seaworthy`.

**Comment by ghostsquad** [comment]
I'll include an example then in my repo to just export and use the export directory
