### ISSUE TITLE
`tk apply` diff error UX improvements

### ISSUE THREAD

**Issue by jdbaldry** [grafana/tanka#324]
When running a `tk apply`, if a diff error is encountered, the command will still prompt the user to "Please type 'yes' to confirm:". As a user, I would prefer not to apply changes unless I have complete information and feel that a diff failure should be notably different to the warning of an empty diff.

It would also be nice to provide a way of avoiding diff issues in some way. For instance, a common source of diff errors is admission webhooks that do not support dry run applies. In these circumstances the entire diff fails and it would be nice for the user to be able specify a way of ignoring the failing resources during the diff stage. Perhaps an inverse of the `-t, --target` flag.

**Comment by Duologic** [comment]
> Perhaps an inverse of the `-t, --target` flag.

Yes, so much yes. I can see it very useful in a test environment where multiple people are working in the same Tanka environment and your branches just drift a bit, you can quickly skip that one or two resources the other dev has applied.
