### ISSUE TITLE
Tanka should manage the namespace resource

### ISSUE THREAD

**Issue by Duologic** [grafana/tanka#325]
In the current setup, one needs to create the namespace manually or with `k.core.v1.namepace`. However, in line with letting Tanka set the namespace on a resource at runtime (based on the environment), it should also create and own a namespace if it doesn't exist already.

In this way, we completely mitigate the need of defining a namespace resource in Jsonnet and we wouldn't need a manual action to get one.

WDYT?

**Comment by ghostsquad** [comment]
What if a namespace is part of the defined set of resources? I typically do this because I include labels and annotations to my namespaces.

Tanka could benefit from a concept of resource deploy ordering? Maybe that should be a separate issue?

**Comment by sh0rez** [comment]
@ghostsquad Tanka already sorts resources by dependency (namespaces + crd's first, etc).

This is probably about having the environment implicitely include it's default namespace, so you don't need to add it manually

**Comment by Duologic** [comment]
Exactly, if a namespace is created and managed in the jsonnet code, tanka should not interfere (also because of backwards compat).

**Comment by ghostsquad** [comment]
> @ghostsquad Tanka already sorts resources by dependency (namespaces + crd's first, etc).

@sh0rez is it possible to manipulate that ordering?

**Comment by ghostsquad** [comment]
Not stale

**Comment by sh0rez** [comment]
This has not come up in recent discussions, namespace handling appears to work just fine. Closing this issue.

Feel free to open another issue if urgent action becomes needed
