### ISSUE TITLE
Prune wants to delete deployments in different namespaces if they have the same environment name

### ISSUE THREAD

**Issue by l-lotz** [grafana/tanka#326]
I have two different projects that use tanka in the same cluster but in different namespaces but are using the same environment name. When calling `tk prune` in project A, tk prune also wants to delete the Deployments, Services, etc. from project B with the same environment name. I guess this could be handled by ensuring that if an object has a namespace, that it must match the namespace of the environment. For objects without a namespace another approach would be needed. For now maybe it would be good if the documentation mentioned that the environment name should be unique for a single kubernetes cluster (or did I miss that?).

**Comment by sh0rez** [comment]
Agreed, that's indeed a bug.

However, Tanka environments can include more than one namespace (even though they shouldn't).

I'd instead suggest adding some sort of project identifier to the label, so that projects can co exist. WDYT?

**Comment by Duologic** [comment]
> For now maybe it would be good if the documentation mentioned that the environment name should be unique for a single kubernetes cluster (or did I miss that?).

At Grafana we have a convention that names the environment <application>/<cluster>.<namespace>, this embeds the namespace and cluster name in the environment label. This explains why we don't have that issue.

Any conflicts at cluster level (eg. RBAC) we come across show up on `tk apply`, these we simply try to mitigate asap.

Documentation would surely cover this to some extent.

**Comment by l-lotz** [comment]
> However, Tanka environments can include more than one namespace (even though they shouldn't).
That is a good point. Another solution could be a command line option for prune to enable the suggested behaviour, but this seems to be very specific to this problem and I think there are more elegant solutions. 
> I'd instead suggest adding some sort of project identifier to the label, so that projects can co exist. WDYT?
I like this idea. Maybe a similar approach to kubernetes with labels in the metadata section of the spec.jsonnet? This would allow having other manners of grouping them other than "project" (like app, customer? or others). A label in tanka named "app" could for example map to a kubernetes label "tanka.dev/label/app".

**Comment by l-lotz** [comment]
> At Grafana we have a convention that names the environment /., this embeds the namespace and cluster name in the environment label. This explains why we don't have that issue.

That is a good idea. I will probably adopt this as well.

> Any conflicts at cluster level (eg. RBAC) we come across show up on `tk apply`, these we simply try to mitigate asap.

I was just thinking about corner cases of my suggested simple solution. It would have a problem even when there are no conflicts. Given project A with a ClusterRole named "clusterrole-a" and project B with a "clusterrole-b". When the environment for project A and B has the same name, `tk prune` can not use the namespace to differentiate between them, as they do not have a namespace. In this case `tk prune` in project A would try to delete "clusterrole-b" even with my original approach. I hope this makes it clearer.

**Comment by Duologic** [comment]
If the clusterRoles have different names, then there is no problem. If they have the same name, then it should only be managed in one place,  that's what I meant by mitigation.

**Comment by l-lotz** [comment]
Ah, right, yeah that makes sense.

**Comment by Duologic** [comment]
#433 makes an attempt at resolving this, maybe the hash should also include a project ID of some kind?

**Comment by sh0rez** [comment]
Closing this issue as technically resolved, given the workaround Duologic suggested. `tk prune` operates on certain assumptions, one being that an environment can be uniquely identified by the environment label.

Users with more complex setups are likely to use full-blown CD like FluxCD anyways.
