### ISSUE TITLE
prune failing when unable to list resources in all namespaces

### ISSUE THREAD

**Issue by retzkek** [grafana/tanka#327]
In the same vein as #301, `tk prune` is failing when running on an OKD/OpenShift cluster, since it's trying to list resources in all namespaces, which I can't do. Specifically in `kubernetes.Orphaned()` at https://github.com/grafana/tanka/blob/e5556f1c851bcfe2f0ec885896642d7c418c692f/pkg/kubernetes/apply.go#L63
(that first empty string tells `GetByLabels()` to add `--all-namespaces` instead of a specific namespace)

Maybe a fix for this could also solve #326?

**Comment by paul-bormans-pcgw** [comment]
Hit the same issue but now on a Google managed platform. Some resources you simply do not have access to as these are managed. It would be nice to reduce the namespaces and resource/apigroups to be considered. So either specify an --include or an --exclude (or both ;-))
