### ISSUE TITLE
Remove hotfix

### ISSUE THREAD

**Issue by simonfrey** [grafana/tanka#328]
https://github.com/grafana/tanka/blob/master/pkg/kubernetes/diff.go#L16-L21:
`prevent https://github.com/kubernetes/kubernetes/issues/89762 until fixed`

This is issue actually is fixed (https://github.com/kubernetes/kubernetes/issues/89762). So might be considerable to remove it.

**Comment by sh0rez** [comment]
While the issue is fixed, specific 1.18.0 still contains it. Upgrading to 1.18.1 or downgrading to 1.17.x solves this.

Agreed, we should change to message to reflect this
