### ISSUE TITLE
Windows: Tanka not running on windows

### ISSUE THREAD

**Issue by c0ffeec0der** [grafana/tanka#329]
When running "tk show environments/loki"

The process would keep running and not end

**Comment by Duologic** [comment]
Can you share a bit more about your environment? How can we reproduce? Do you have some code available?

**Comment by c0ffeec0der** [comment]
The environment is windows 10 version 2004

I was following the instructions on https://grafana.com/docs/loki/latest/installation/tanka/

When reaching step :
- Run "tk show environments/loki" to see the manifests that will be deployed to the cluster.

The process keep running and does not end

**Comment by JohnRusk** [comment]
I have the same bug.
