### ISSUE TITLE
`tk lint` ?

### ISSUE THREAD

**Issue by sbarzowski** [grafana/tanka#342]
On the go-jsonnet side, I have just merged the first reasonable implementation of the linter. Would you consider integrating it with Tanka? I think it would be especially useful to new users, because often it can produce a clear message about something that would otherwise result in an ugly stack trace.

The API is dead simple:
```
func LintSnippet(vm *jsonnet.VM, output io.Writer, filename, code string) bool
```

It takes a filename and the source as a string and prints the result to `output`. It also takes `vm`, so that it can follow imports. It only reports errors in the directly passed file, but imports are very important, because they allow us to detect bad usage of the library.

I plan to later add a version which takes multiple files and processes them all at once more efficiently (processing common imports only once).

**Comment by sh0rez** [comment]
Totally!! I've been following your PR for some time to do exactly what you suggest once merged. Thanks a lot for the heads up :)

**Comment by Duologic** [comment]
Related to jsonnet-lint: https://github.com/grafana/tanka/pull/427

**Comment by Duologic** [comment]
With #427 in v0.13.0, this can be achieved with 
```
JSONNET_PATH=$(tk tool jpath .) jsonnet-lint myFile.jsonnet
```
Do we want to do anything more?

**Comment by sh0rez** [comment]
I'd like to eventually bring `tk lint` to life, which lints all files an environment uses. IIUC the `jsonnet-lint` command only lints the current file. Using `tk tool imports` we know the imported files anyways, so it should be fairly straight forward to combine those

**Comment by sbarzowski** [comment]
> IIUC the `jsonnet-lint` command only lints the current file

FYI right now the API allows linting only one file, but actually it still loads all transitive dependencies (so it can figure out "types" of library objects etc). It makes sense to run the linter for all interesting files in one go (to avoid duplicating work in common deps), so I plan to extend the API and CLI to allow that.

> Using tk tool imports we know the imported files anyways, so it should be fairly straight forward to combine those

You may want to consider just running it of all user's files in a Tanka project. Usually we are not interested in warnings from 3rd party libraries I think.
