### ISSUE TITLE
Use other languages than Jsonnet

### ISSUE THREAD

**Issue by masaeedu** [grafana/tanka#343]
Hello there. I was wondering if it's possible for me to use tanka without having to follow the project structure or buying into Jsonnet etc. If I can produce a big blob of JSON analogous to what main.jsonnet normally evaluates to using some other mechanism (some other programming language, etc.), can I just pass it to tanka and ask it to extract the Kubernetes resources and apply it?

I don't want to deal with jb and jsonnet and ksonnet and so on and can more easily generate the configuration I'm interested in without those.

**Comment by sh0rez** [comment]
Hi, that's an interesting idea we didn't consider too much yet.

The tk is currently built, there is no way around Jsonnet. This may change in another major version in the future.

Luckily, every JSON is valid Jsonnet, so you could obtain it any way you want. You have two options here:

#### 1. Writing to a file, importing it
Nix, Python, Cue or whatever you want to use should write the JSON to a file with a well known name next to `main.jsonnet`, which should have the following contents:

```jsonnet
import "myFile.json"
```

Keep in mind this evaluates the JSON as Jsonnet so make sure it is just plain JSON

#### 2. Going a bit crazy
If you don't want to use a file, you can try importing `/dev/stdin`:

```jsonnet
// main.jsonnet
import "/dev/stdin"
```

Now, this will work:

```bash
$ myJsonCommand | tk show .
```

Keep in mind I have no idea whether this has unexpected side effects, but it seems to work in my local testing.

**Comment by masaeedu** [comment]
> with a well known name next to main.jsonnet

The problem is I don't want to create that whole folder structure with vendor/lib/lockfile etc. at the root. If I just try to pass a file directly to `tk` it seems it is not happy and it produces an error message indicating that I need to follow the directory structure.

**Comment by malcolmholmes** [comment]
Dare I ask, once you remove Jsonnet and the directory structure, what is left that is worth having??

**Comment by masaeedu** [comment]
@malcolmholmes The traversal that pulls out the resources from the arbitrarily structured JSON, and the logic that applies and deletes them in the correct order. I believe the diff logic can be handled by `kubectl` after the resources are extracted and dumped into a big YAML file, but I'm not sure if tanka is doing something else on top.

**Comment by sh0rez** [comment]
@masaeedu for working with already exists, the following should suffice:

```
/jsonnetfile.json OR tkrc.yaml
/main.jsonnet
```

While being one folder, this is a valid environment. Using the `import "/dev/stdin"` trick, you could use this to pass in whatever data you want into Tanka.

---

We might be able to extract pieces such as extracting from the big object, etc. into `tk tool` commands.

To get a better idea how that could look like, could you please describe:

- what you are trying to achieve
- why that doesn't work right now
- what a perfect workflow would look like

**Comment by masaeedu** [comment]
@sh0rez I didn't realize that was all that's needed. That satisfies my use case, thanks.
