### ISSUE TITLE
Support for non-native resources (e.g. Istio)

### ISSUE THREAD

**Issue by xvzf** [grafana/tanka#344]
Hello,

First of all, nice project 👍 

Is there an intuitive way to interface with other resources? E.g. the Istio CRDs?

Cheers,
Matthias

**Comment by Duologic** [comment]
You can perfectly well use CRDs with Tanka, it will happily deploy them.

**Comment by sh0rez** [comment]
Hi, Tanka has no assumptions about the resources it deploys.

The  Jsonnet library for Kubernetes that are frequently used (`github.com/ksonnet/ksonnet-lib`, or the newer `github.com/jsonnet-libs/k8s-alpha`) only include the "real" k8s kinds.

Because these libraries only return the objects you would write as yaml otherwise, there is nothing stopping you from doing to so in Jsonnet for your CRD's:

```jsonnet
local k = import "k.libsonnet";

{
  // shorthand form provided by the library
  deployment: k.apps.v1.deployment.new("grafana", 1, [k.core.v1.container.new("grafana", "grafana/grafana")])

  // JSON syntax still possible
  customThing: {
    apiVersion: "cert-manager.io/v1alpha2",
    kind: "ClusterIssuer",
    metadata: { name: "myClusterIssuer" },
    spec: {
      // ...
    }
  }
}
```

Let me know if that works for you

**Comment by xvzf** [comment]
Let me elaborate more, what I target is leveraging the same "workflow" than with other resources, e.g.:

```jsonnet
(import "ksonnet-util/kausal.libsonnet") +
{
  _config:: {
    test: {
      name: "hello-world"
      port: 3000,
      host: "grafana",
    },

  local virtualservice = $.networking_istio_io_.v1beta1.virtualservice,

  test: {
    virtualservice: virtualservice.new(
      name=$._config.test.name,
      hosts=[  $._config.host  ],
      // ...
    ),
  },
}
```

I'm not sure if this is possible with `ksonnet-lib` but if I got the design correctly it builds the library based on the served OpenAPI definition -> on a "live" cluster this definition can be extended via CRDs.

Just putting an idea here: having a `tk import-crds` would be a very nice feature

**Comment by sh0rez** [comment]
Ah! What you suggest will definitely possible in near future, as our own https://github.com/jsonnet-libs/k8s generator continues to mature.

It's not there yet (some hardcoded references to kubernetes), but it could totally operate with any swagger spec it receives, including those of custom resource definitions

**Comment by sh0rez** [comment]
This is the tracking issue on the generator project: https://github.com/jsonnet-libs/k8s/issues/3.

Closing it here :)
