### ISSUE TITLE
Confirmation prompt not working on Windows

### ISSUE THREAD

**Issue by JohnRusk** [grafana/tanka#347]
Here's an example (running from Windows Powershell)

```
>tk apply environments/default
Applying to namespace <REDACTED>
Please type 'yes' to confirm: yes
aborted by user
```

Notice that when I type "yes", `tk` replies with "aborted by user".

A (temporary) workaround is to add the `--dangerous-auto-approve` flag. (I like the name, by the way!)

**Comment by sh0rez** [comment]
This is probably related to this code:

https://github.com/grafana/tanka/blob/931373ab37ece35da9de536d9cd883f3e8150ee7/pkg/term/alert.go#L16-L23

Probably the different line endings on Windows are the problem. It would need `\r\n`.

However, it seems like there is no `os` constant in Go for this?!

**Comment by JohnRusk** [comment]
Yeah, I don't think there is a constant. But this would presumably work:

```
if strings.Trim(read, "\r\n") != approval {   // trim all EOL chars from read, instead of adding any to approval
    return ....

```

**Comment by sh0rez** [comment]
Good idea! Wanna try that out and if it works, create a PR?

**Comment by JohnRusk** [comment]
Will do.

**Comment by JohnRusk** [comment]
Thanks for the reminder, StaleBot.  I'm struggling to find time for this.  May or may not get to it.  Sorry about that sh0rez.

**Comment by nlowe** [comment]
This is still a problem in the most recent release and should be re-opened.

**Comment by JohnRusk** [comment]
Nice @sh0rez . Sorry I never got time to attempt doing this for you!
