### ISSUE TITLE
tk init requires admin rights on Windows

### ISSUE THREAD

**Issue by JohnRusk** [grafana/tanka#348]
Otherwise you get an error making a symlink.

Is there some way it could either be done with out admin rights, or documented [here](https://tanka.dev/tutorial/jsonnet#creating-a-new-project) that they are required for `tk init` (specifically for the `jb` command that is used by tk init)?

**Comment by sh0rez** [comment]
Correct, jsonnet-bundler requires symbolic links to operate the way it does currently. That might change in the future.

However, a quick Google search revealed, enabling Developer Mode on Windows 10 should suffice to relax the requirement for admin rights: https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

**Comment by JohnRusk** [comment]
OK. Maybe just needs a note in the [tutorial page](https://tanka.dev/tutorial/jsonnet#creating-a-new-project), where `tk init` is first introduced, to say something like, "jb creates symbolic links. On Windows, this means you must run this step with Admin rights OR enable [Windows 10 Developer mode](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/)"

**Comment by Duologic** [comment]
/unstale

@JohnRusk Would you be willing to create a PR for this?

**Comment by JohnRusk** [comment]
I would love to.  But I just can't find time at the moment.  Maybe if we leave this open, I'll have time in a month or so...
