### ISSUE TITLE
request: support more of the normal jsonnet input flags

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#353]
This is a request to have Tanka support some of the other standard flags for use with jsonnet:

```
--tla-code
--tla-code-file

--tla-str
--tla-str-file

--ext-str-file
--ext-code-file

-J / --jpath
```

Also, the naming of these should likely be standard between TK and Jsonnet for ease of discovery. I filed a separate issue for that here: #354

**Comment by sh0rez** [comment]
TLAs and extVars are implemented, using the same flags as Jsonnet does.

JPATH has its own tracking issue: #365 

Closing as there is nothing to do here anymore :)

**Comment by lukasmrtvy** [comment]
@sh0rez but `--ext-code-file` is not implemented..., seems there isnt a way how to dynamically include file, for example use case with sops:
```
sops exec-file secrets.enc.yaml 'tk show . --ext-code-file secrets={}'
```
nor
```
local secrets = import std.extVar('secrets_path'));
```
```
sops exec-file secrets.enc.yaml 'tk show . --ext-str secrets_path={}'
```
can not work..  any workaround? 

> sops exec-file - execute a command with the decrypted contents as a temporary file

thanks

**Comment by davidovich** [comment]
@lukasmrtvy Assuming you have a tanka top level function that takes a `secrets` object in parameter, I am able to inject secrets in Tanka in this manner:

`sops exec-file mySecretFile.enc.json 'tk apply --tla-code secrets={secret: import \"{}\"} environment'`

Hope that helps.

**Comment by danihodovic** [comment]
--ext-code-file would be useful for injecting secrets from temporary files
