### ISSUE TITLE
unable to update/deploy default serviceAccount on first apply

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#360]
## Description

When creating a namespace, and including updates to the default service account, I get an error:

```
Error from server (AlreadyExists): error when creating "STDIN": serviceaccounts "default" already exists
```

This is resolved by applying a second time.

**Comment by ghostsquad** [comment]
unstale

**Comment by sh0rez** [comment]
Can we do something about this? Tanka attempts to sort objects to satisfy dependencies, but most of the work is done by kubectl.

**Comment by ghostsquad** [comment]
@sh0rez is tanka running kubectl `create` or `apply`? I would imagine that this wouldn't be a problem with `apply`, but I'm not sure.

**Comment by sh0rez** [comment]
It is indeed running apply

**Comment by ghostsquad** [comment]
Hmm.. maybe it's an antipattern to use/modify the default service account in the namespace.

**Comment by malcolmholmes** [comment]
I'm inclined to agree. Only use resources you directly create.
