### ISSUE TITLE
automatic helm chart resolution

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#364]
Currently when using freshly introduced `helm.template`, the local Helm environment needs to be properly set up with all required Charts available, etc. This is not declarative and a very manual step.

Internal discussions showed that there is a need for strong reproducibility here, similar to what the `jsonnetfile.lock.json` provides. But also the workflow shouldn't be manual, so we need to find a middle ground.

Everybody with opinions / ideas on this is welcome to express those!

**Comment by sh0rez** [comment]
Design document published: https://docs.google.com/document/d/171F0cm_VliMStmHe6oy5pAbuXihr-7Cb5yD-vmwqpP8/edit#

Progress tracking:

- [ ] Library-relative Chart importing
  - [ ] Path resolution in native function
  - [ ] `std.thisFile` in `helm-util`
- [ ] Declarative Chart vendoring

**Comment by chancez** [comment]
Any reason to not just use `Chart.yaml` and the `helm fetch/pull` internals versus #367 which has it's own format?

**Comment by sh0rez** [comment]
@chancez how would that work? Keep in mind we are not building a Chart here, we want a way to define the contents of a 'vendor'-like directory for Jsonnet libraries to have the Helm Charts they need in their own source tree

**Comment by chancez** [comment]
I'd think it would work the same as the `Chartfile` for fetching, but the organization once fetched would be modified by tanka or another tool to get the on-disk layout you want (in vendor, or somewhere else for example).

**Comment by sh0rez** [comment]
Fully implemented in https://github.com/grafana/tanka/pull/367, https://github.com/grafana/tanka/pull/370 and https://github.com/grafana/jsonnet-libs/pull/338
