### ISSUE TITLE
-e function on tk eval

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#377]
The Jsonnet CLI allows passing code to be executed instead of executing a file.

This could be used to execute something like `(import 'main.jsonnet').a.b`. If used from `tk eval` like this, it would allow introspection of the json tree, including hidden values, which would be extremely valuable in debugging Jsonnet/Tanka scripts.

**Comment by sh0rez** [comment]
Implemented in https://github.com/grafana/tanka/commit/a68d33d18391ca9def098e62cc7a47130f7bb4b7
