### ISSUE TITLE
Time for 0.11.2 or 0.12 release?

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#384]
Can we get a new release? There's a few issues that I've been patiently waiting for:

#372 #354 #353 #352 among others

**Comment by sh0rez** [comment]
Totally! We just released another pre-release of 0.12, in case we don't see any major issues 0.12 comes early next week!

**Comment by Duologic** [comment]
https://github.com/grafana/tanka/releases/tag/v0.12.0
