### ISSUE TITLE
Environment name in different env subcommands is either the last element of the path or a path relative to the root dir

### ISSUE THREAD

**Issue by mwasilew2** [grafana/tanka#397]
There seems to be some inconsistency between different `tk env` subcommands around what is treated as the environment name. `tk env add environments/jaeger/production` will create `spec.json` with `metadata.name: production`, but `tk env set environments/jaeger/production --server-from-context minikube` will set it to `metadata.name: environments/jaeger/production`.

Should `tk env add` perhaps be switched to using a relative path for inferring the name of the namespace, something similar to https://github.com/grafana/tanka/blob/master/pkg/tanka/parse.go#L112 instead of `cfg.Metadata.Name = filepath.Base(path)` (https://github.com/grafana/tanka/blob/master/cmd/tk/env.go#L160 ) ?

**Comment by sh0rez** [comment]
Hi, good spot!

Yes, the code in `pkg/tanka/parse.go` is correct. The environment name shall be the relative path from the project root. Actually, the environment name is never read from the file, but inferred from the directory structure when loading the config.

Still it makes perfect sense to fix `tk env add`. Would you like to do that?

**Comment by mwasilew2** [comment]
@sh0rez tried fixing it here: https://github.com/grafana/tanka/pull/404

**Comment by sh0rez** [comment]
Fixed in #404
