### ISSUE TITLE
Intellij and Vscode plugins can't find dependencies

### ISSUE THREAD

**Issue by dave08** [grafana/tanka#406]
The way tk implements imports complicates using tooling from IDE's, which means no code-completion and forcing new users to dig into all the libsonnet files to find all the parameters functions and objects already declared... maybe have an extra file in the environment to hard-code those imports for tooling (either managed by tk init or jb or both)?

**Comment by Duologic** [comment]
_disclaimer: I have zero experience with these IDEs_

I'm not sure which plugins you refer to, can you state that more clearly?

The Heptio vscode plugin for Jsonnet is archived, but assuming you refer to this and still use it, there is a customization option that lets you set the JPATH with `jsonnet.libPaths`:  https://github.com/heptio/vscode-jsonnet/blob/0957d4235be011f2f2ac2f8af51cd7927852eeaa/README.md#customization

You can try to replicate this in here: 
https://github.com/grafana/tanka/blob/1220d149a4f3210d8932f41f415599e88cbbee41/pkg/jsonnet/jpath/jpath.go#L56-L62

If you figure it out, would you mind sharing that here? Extra karma points for a PR in the docs. :wink:

**Comment by dave08** [comment]
Got it working partially (ctrl-click to go to any referred function or object in the jsonnet being worked on) in Intellij Ultimate using (from a file in the lib/ folder... for environments/xxx/ -- ../../ would be needed...):
```
local k = import "../vendor/github.com/jsonnet-libs/k8s-alpha/1.17/main.libsonnet";

{
  local deploy = k.apps.v1.deployment,
  local container = k.core.v1.container,
  local port = k.core.v1.containerPort,
  local service = k.core.v1.service,
  local servicePort = k.core.v1.servicePort,
  local lor = k.core.v1.localObjectReference,
```
But that involves manual tweaking... I guess the real solution is to find a way to add support for -J in the plugins as suggested, or just get Tanka to do this automatically... and make it a standard in how to use Tanka. But then I'm sure there's some kind of reasoning why Tanka does things the way it does currently (depending on -J instead of hard-coded imports...).
