### ISSUE TITLE
`tk export` does not handle ksonnet's roleList

### ISSUE THREAD

**Issue by agrahamlincoln** [grafana/tanka#410]
**Problem**: Using `tk export` with kube-prometheus results in the following error:

File 'environments/dev/manifests/tanka/rbac.authorization.k8s.io-v1.Role-prometheus-k8s.yaml' already exists. Aborting

**How to reproduce the issue**:

Setup a tanka environment with kube-prometheus.
```bash
tk init
tk env add environments/dev
jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@release-0.4
```

Add the following `main.jsonnet` to the environment
```json
// environments/dev/main.jsonnet
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet');
{ role: kp.prometheus.roleSpecificNamespaces }
```

Try to export the manifests
```bash
tk export environments/dev/ environments/dev/manifests/tanka --merge
```

**Other notes:**

- Most other commands (diff, apply, show) work fine. It seems this is related to the file naming and error handling.
- I'm unsure if this should be brought up with ksonnet instead, maybe it should use a List type object instead of creating a yaml stream?
- The [roleList used by kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/blob/aee7f28bcdaca57a746c2ae96b3649d163bc2307/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L161) comes from ksonnet.beta.3 which is pretty old - maybe they should use a newer one?

**Comment by Duologic** [comment]
I'm sorry you didn't get a response back. I missing some context and implementation details, so I'm unsure if this might solve your problem.
The export doesn't include the namespace of an object in the file name, judging from `roleSpecificNamespaces` I assume that is what is causing this. You can use a different naming pattern on export to solve that: https://tanka.dev/exporting#filenames
Feel free to reopen in case this doesn't solve your problem.

**Comment by PatTheSilent** [comment]
For anyone furiously googling like me, exporting with `--format  '{{.apiVersion}}.{{.kind}}-{{.metadata.name}}-{{.metadata.namespace}}'`  does in fact help, just as @Duologic  suggests.
Due to kube-promethues creating roles in a couple of namespaces https://github.com/prometheus-operator/kube-prometheus/blob/release-0.7/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L15
