### ISSUE TITLE
Is there a way to get a "full diff" before running BOTH `tk apply` and `tk prune`?

### ISSUE THREAD

**Issue by curusarn** [grafana/tanka#416]
I can run `tk diff` (or just `tk apply`) to see what changes will `tk apply` do.
I can run `tk prune` to see what changes it is going to do.

I would like to be able to see all the changes that BOTH `tk apply` and `tk prune` is going to do.

I tried running `tk diff` and `tk prune` to get the "full diff".
Unfortunately, `tk prune` fails when there are new k8s resources in Jsonnet that are not applied to the cluster yet. 
To provide an example, I have added a PodDisruptionBudget to Jsonnet and `tk prune` failed:
```
❯ tk prune environments/env1/dev                                                                 
fetching UID's .. Error from server (NotFound): poddisruptionbudgets.policy "app1" not found
```

I think this issue is a small fix that I could implement myself but I want to see the bigger picture instead of focusing on a single issue. I'm also aware that `tk prune` is still a new feature so I assume that is why it is a separate command instead of being a part of `tk apply`.

Do you plan to eventually merge the `tk prune` into the `tk apply` command?

**Comment by curusarn** [comment]
I would really like to get some response to this. I'm willing to contribute but I would like to get some input so that I don't end up with changes that won't get merged to the upstream.

**Comment by malcolmholmes** [comment]
tk prune is separate because it is dangerous. Therefore we typically run it less often.

Having a `tk diff --with-prune` option would strike me as useful.

What changes do you propose?

**Comment by Duologic** [comment]
That sounds like a nice option. @malcolmholmes how is the diff dangerous?

I can see you need to have a clean apply-diff before you can get the prune, right? Maybe we need to generate the manifests locally and download the manifests from Kubernetes, then compare them locally to get both the apply and prune differences.

**Comment by malcolmholmes** [comment]
Diff isn't dangerous prune is. I was trying to say that there is a reason why apply/prune are separate, but that needn't apply to diff.

**Comment by curusarn** [comment]
Having `diff --with-prune sounds good and it solves my issue. Thanks.

I will implement it and submit an MR when/if I need it.
