### ISSUE TITLE
namespace setting for helm.template in lib not take effect

### ISSUE THREAD

**Issue by dfang** [grafana/tanka#418]
i'm trying to consume helm chart in lib/traefik and lib/cert-manager, and import them to environments/default/main.jsonnet, and deploy them to the according namespace 

```
λ  tree -L 2
.
├── chartfile.yaml
├── charts
│   └── traefik
├── environments
│   └── default
├── jsonnetfile.json
├── jsonnetfile.lock.json
├── lib
│   ├── cert-manager
│   ├── k.libsonnet
│   └── traefik
└── vendor
    ├── github.com
    ├── helm-util -> github.com/grafana/jsonnet-libs/helm-util
    ├── ksonnet-util -> github.com/grafana/jsonnet-libs/ksonnet-util
    └── ksonnet.beta.4 -> github.com/ksonnet/ksonnet-lib/ksonnet.beta.4

12 directories, 4 files
```

in environment/spec.json,   namespace is default

lib/traefik/traefik.libsonet

```
local helm = (import "github.com/grafana/jsonnet-libs/helm-util/helm.libsonnet").new(std.thisFile);

{
  traefik: helm.template("traefik", "../../charts/traefik", {
    namespace: "traefik",
    values: { }
  })
}
```
in main.jsonnet

```
(import "traefik/traefik.libsonnet")
```

```
$ tk export environments/default/
$ ag namespace tmp/
tmp/traefik.containo.us-v1alpha1.IngressRoute-traefik-dashboard.yaml
12:  namespace: default

tmp/v1.Service-traefik.yaml
10:  namespace: default

tmp/v1.ServiceAccount-traefik.yaml
10:  namespace: default

tmp/rbac.authorization.k8s.io-v1.ClusterRoleBinding-traefik.yaml
17:  namespace: traefik

tmp/apps-v1.Deployment-traefik.yaml
10:  namespace: default
```

however in `tk show environments/default/` outputs, namespace could be default or traefik

**Comment by Duologic** [comment]
If a manifest doesn't have a namespace set, it will use the namespace defined in spec.json.

Tanka simply calls `helm template --namespace traefik` here, apparently this has been an issue that Helm is not willing to solve and is usually resolved by setting the namespace in the manifest templates. Ref: https://github.com/helm/helm/issues/3553#issuecomment-521424132

To workaround this issue, we could add this function to the helm-util library:

```jsonnet
{
  setNamespace(object, namespace)::
    this.patchKubernetesObjects(
      object,
      {
        metadata+: {
          namespace: namespace,
        },
      }
    ),
}
```

**Comment by dfang** [comment]
@Duologic so if your pr is merged, how should i call in traefik.libsonet ?
just a noob on jsonnet, sorry :)

**Comment by Duologic** [comment]
You can wrap it around `helm.template()`

**Comment by SnehaMore20** [comment]
Hi @Duologic, how can I use the function patchKubernetesObjects to set namespace to all the helm objects I have. Sorry just started with jsonnet and could not figure that out from documentation.

Here is my main.libsonnet.

```
local helm = (import "./helm-util/helm.libsonnet").new(std.thisFile);
{
  thanos(name, namespace):: [
  helm.template('name', './charts/thanos', {
    values: 
    {
       ....
    }
  })
  ]
}
```

I tried something like this and this is definitely not correct:
```
local helm = (import "../vendor/helm-util/helm.libsonnet").new(std.thisFile);
{
  thanos(name, namespace, env, stage, bucket_name, aws_region, thanosCpu, thanosMemory):: [
  helm.template(name, '../charts/thanos', {
    values: 
    {
      .....
    }
  })+
  helm.patchKubernetesObjects(object, 
        {
        metadata+: {
          namespace: namespace,
        },
      })
  ]
}
```
Thanks in advance

**Comment by Duologic** [comment]
It doesn't work as a mixin, you have to execute it on the outcome of helm.template(). Like so  `helm.patchKubernetesObjects(helm.template(...), {})`

**Comment by sh0rez** [comment]
Closing this issue as it appears solved. If further questions arise, please start a discussion: https://github.com/grafana/tanka/discussions
