### ISSUE TITLE
`tk tool charts vendor` idempotence

### ISSUE THREAD

**Issue by craigfurman** [grafana/tanka#419]
It'd be neat if `tk tool charts vendor` was idempotent, clobbering the contents of `./charts` with whatever is specified in `chartfile.yaml`. In this way its behavior would be similar to `jb install` or other dependency management commands.

What do you think of this idea? Would you be interested in a PR that implements it?

**Comment by sh0rez** [comment]
Loving it! Go ahead with a PR and feel free to reach out to me or any other team member if you get stuck :)

**Comment by craigfurman** [comment]
The behavior in tk 0.12 (exiting with an error when `tk tool charts vendor` is called for an already vendored chart) has been changed to not exit with an error in https://github.com/grafana/tanka/pull/402 and https://github.com/grafana/tanka/issues/401.

I propose to change this to overwrite charts with the version specified in chartfile.yaml, if a different version is already downloaded. PR incoming.

**Comment by craigfurman** [comment]
I've implemented this in https://github.com/grafana/tanka/pull/420. Let me know what you think!

**Comment by Duologic** [comment]
Thank you for your contribution, #420 is merged and available in v0.13.0.
