### ISSUE TITLE
Improve error messaging when diff fails

### ISSUE THREAD

**Issue by dannykopping** [grafana/tanka#421]
When a diff fails, the messaging to the end user is not terribly clear:

```
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Error diffing: listing known api-resources: exit status 1
Applying to namespace 'default' of cluster 'k3d-grafana-agent' at 'https://0.0.0.0:42743' using context 'k3d-grafana-agent'.
Please type 'yes' to confirm:
```

In this scenario, I would expect a warning message (preferably in an attention-grabbing colour or font thickness) to alert me that something has not worked out and applying these changes blindly may lead to unexpected outcomes.

**Comment by anarcher** [comment]
Even if the metric adapter is failing in the apiService, it would be nice if it was diffing.
