### ISSUE TITLE
Grafana Slack

### ISSUE THREAD

**Issue by fculpo** [grafana/tanka#423]
Hi,

I wanted to join the community Slack but it is virtually impossible to join as it enforces an everquote.com address.
Is this Slack still alive and/or am I missing something ?

Also the mailing lists seems empty.

**Comment by sh0rez** [comment]
You did try https://grafana.slack.com, right? Seems to work just fine for me

**Comment by fculpo** [comment]
Yes, and when trying to create an account:

- via google: error = The email address must match one of the domains listed below. Please try another email.
- via manual mail = i can only use an everquote.com mail

![image](https://user-images.githubusercontent.com/325117/99536612-e2babc80-29aa-11eb-8c1d-d3a3a43f11a0.png)

**Comment by malcolmholmes** [comment]
This is a slack issue not a Tanka one. You could talk to your tech support about this. Alternatively, you could open the slack link in a different browser profile that hasn't been logged into with a work email.

I'm gonna close this. Feel free to open if you have further issues.

**Comment by malcolmholmes** [comment]
Reopening after another report of same issue.

**Comment by malcolmholmes** [comment]
Immediate solution, just visit https://grafana.slack.com, which should work fine. We're investigating what is wrong with the link you are trying.

**Comment by fculpo** [comment]
I was using https://grafana.slack.com from the beginning.

But it seems that the correct entry point is actually https://slack.grafana.com/ which allows to request an invitation to the workspace

**Comment by malcolmholmes** [comment]
We found three. The two you mentioned, plus grafana.slack.com/signup which was broken. I will check tomorrow whether we found a permanent solution.
