### ISSUE TITLE
Make tanka available as kubectl plugin

### ISSUE THREAD

**Issue by metalmatze** [grafana/tanka#45]
Looking at this project, I think it should be possible to make this interface with the kubectl plugins and distribute via krew.
https://github.com/kubernetes-sigs/krew

Let me know what you think!

**Comment by tomwilkie** [comment]
Hi @metalmatze!  I really don't get the point of the current kubectl plugins; AFAICT they only let you replace a hyphen with a space (ie `kubectl-tanka apply ...` with `kubectl tanka apply ...`).

There is nothing stopping us doing this, but also why would we?  Or am I missing something?

What I really want is to be able to do `kubectl apply -f main.jsonnet` and have some way of kubectl running tanka to convert the jsonnet into yaml...

**Comment by metalmatze** [comment]
Next to having the "feeling" of being integrated with kubectl, krew should offer easier distribution for people to get tanka. Also updating would be easier through AFAIK.
Did I forget anything @lbb?

I basically simply wanted to start a discussion if it would make sense and what people think.

No hard feeling from my side if we don't do this.

**Comment by sh0rez** [comment]
I feel like this is another nice way of distributing Tanka, if somebody wants to take this up I would be happy to review it!
