### ISSUE TITLE
--target does not accurately describe what it needs

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#452]
The help message for `--target` is

```
-t, --target strings           only use the specified objects (Format: <type>/<name>)
```

but what is `type`? Kubernetes doesn't use that language for objects. There is `apiVersion` and `kind` and maybe a combination of those, which I think is called `apiGroup`?

Additionally, it doesn't say if this parameter can be passed multiple times or not

**Comment by sh0rez** [comment]
You're right, the format should actually read `<kind>/<name>`. And yes, it can be specified multiple times. Interested in creating a PR to clarify this?

**Comment by ghostsquad** [comment]
Indeed I am. Easy enough. ;)
