### ISSUE TITLE
feature: apply --selector

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#453]
This is a feature request for similar functionality as `kubectl get` in that it supports:

```
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
      --server-print=true: If true, have the server return the appropriate table output. Supports extension APIs and
CRDs.
```

It would be really cool if you could apply using a set of label selectors.

If this feature is accepted, I'd like to contribute to this code base!

**Comment by sh0rez** [comment]
I like the idea! 

The filtering framework of `pkg/process` should allow fairly easy integration: https://github.com/grafana/tanka/blob/17baa356eaea5a30c4a88a8950e2dbefb51636e1/pkg/process/filter.go#L13

Take a look at how `--target` / `-t` is implemented, you should be able to hook label filtering in there as well :)

**Comment by sh0rez** [comment]
@ghostsquad still on this?

**Comment by ghostsquad** [comment]
@sh0rez ya, I still want this, looking for some time to complete this still.

**Comment by ghostsquad** [comment]
Not stale

**Comment by ghostsquad** [comment]
Hey, I'd like to reopen this @sh0rez - a lot going on at work, but I think this is still something that's needed. I'm actually not sure if I will have the time to complete this, so I'll open this up if someone else wants to work on this feature. If no one takes it, I'll keep it on my plate.

**Comment by ghostsquad** [comment]
I really need this now... I'm far into a project where I'm generating manifests for 23 different "addons" for a kubernetes cluster. Manifests are generated (via terraform, but that's a separate story), but need to be applied in waves.

1: delete some addons like aws-node, coredns, and heapster that come pre-installed
2: redeploy those addons and several others that are very low level, or provide CRDs
3: generate secrets and seal them using sealed-secrets
4: deploy remaining addons that had a dependency on previous or that needed a sealed-secret
