### ISSUE TITLE
Adding text template evaluation to native functions

### ISSUE THREAD

**Issue by curusarn** [grafana/tanka#479]
Sometimes I would like to patch config files that I put into config maps. I don't usually have control over the format of the config file so I can't parse it as Json and then use Jsonnet to patch it. It makes a lot of sense to me to patch the configs using Tanka because in Tanka I already have all the information and variables I want to patch into to config files.

Simple string formatting works for the simple cases but I do run into cases where I need conditions and loops.
Would it make sense to add go template (or some other text template) evaluation to native functions?

**Comment by sh0rez** [comment]
Hi! Could you elaborate on the use-case? Jsonnet itself is a fairly capable language, so it would surprise me if you run into cases that can't be solved by standard Jsonnet means. 

JSON-similar config formats (TOML, YAML, JSON, INI) can be represented in Jsonnet and marshalled. For other formats, it's often possible to pre-compute the complex part and only string-format it in into place.

We've considered this before, and always found ways to do it without introducing templating support, but let's see :)

**Comment by curusarn** [comment]
I'm currently facing a problem with templating HAProxy configs which use custom format. I probably could manually construct the complicated parts and then string-format them into place. However, I feel like that would mean writing a lot of error prone code which will be hard to maintain and could be better expressed with text templating.

**Comment by Duologic** [comment]
I've seen `importstr 'templatefile') % config_dict` in the wild, would that help? If not, feel free to ask for help in the discussion section.

**Comment by curusarn** [comment]
Sorry for the long silence. Here is an example constructing configs using tanka:
```
local targetExt = "<REDACTED>";
local targetInt = "<REDACTED>";
local domainsExt = [
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
];
local domainsInt = [
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
];

{
  apiVersion: "v1",
  kind: "ConfigMap",

  metadata: {
    name: "coredns",
    namespace: "kube-system",
    labels: {
      "eks.amazonaws.com/component": "coredns",
    },
  },

  data: {
    Corefile:
      |||
        .:42 {
            errors
            health

            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              upstream
              fallthrough in-addr.arpa ip6.arpa
            }
      |||
      + "\n"
      + std.join(
        "",
        ["    rewrite name " + d + $._tld + " " + targetInt + "\n" for d in domainsInt],
      )
      + std.join(
        "",
        ["    rewrite name " + d + $._tld + " " + targetExt + "\n" for d in domainsExt],
      )
      + "\n"
      +
      |||
        #
            prometheus :1234
            forward . /etc/resolv.conf
            cache 30
            loop
            reload
            loadbalance
        }
      |||,
  },
}
```

Is there some better way to construct configs like this one?
It seems to me that it would be much cleaner to describe it using text templating.
What do you think?

**Comment by Duologic** [comment]
This kind of templating is indeed not easy. 

We have moved the 'template' file into a separate file and `importstr` that, it makes things a bit more readable.Here is a snippet directly coming from our internal dns lib:

```jsonnet
{
  local corefileStr = importstr 'files/Corefile',
  local corefile = std.strReplace(
    std.strReplace(
      corefileStr,
      'CLUSTER_NAME',
      this._config.cluster_name
    ),
    'ALTERNATIVE_DNS_NAMES',
    std.join(' ', this._config.coredns.alternative_dns_names)
  ),
}
```

**Comment by curusarn** [comment]
I can see that this works okay for your config but let's look at how the config I posted above would look something like like:
```
local targetExt = "<REDACTED>";
local targetInt = "<REDACTED>";
local domainsExt = [
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
];
local domainsInt = [
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
  "<REDACTED>",
];
{
  local rewriteBlockInt = std.join(
    "",
    ["    rewrite name " + d + $._tld + " " + targetInt + "\n" for d in domainsInt],
  ),
  local rewriteBlockExt = std.join(
    "",
    ["    rewrite name " + d + $._tld + " " + targetExt + "\n" for d in domainsExt],
  ),
  local corefileStr = importstr 'files/Corefile',
  local corefile = std.strReplace(
    std.strReplace(
      'REWRITE_BLOCK_INT',
      rewriteBlockInt
    ),
    'REWRITE_BLOCK_EXT',
    rewriteBlockExt
  ),
}
```
I like that this way we can get rid of the ugly string blocks. And I think it works well for simple configs.

However, I really dislike that the config is now effectively split between two files - the jsonnet code and the template. Unlike in your config, I need to construct whole lines/blocks of the config. I don't just replace values I need to replace actual pieces of the config with correct syntax. For example, I need to know that the config uses 4 spaces for indentation. Splitting the knowledge about the config format between the jsonnet code and the template is imho very fragile.

Maybe this is acceptable with this specific config. But imagine a config where you need to generate whole blocks of text. I think that would become very error-prone and hard to maintain.

I think that with text-templating I could keep all the knowledge about the format of the config in the config itself. And I would only inject values into the template from jsonnet.

In ideal world, I would have some way to represent the corefile as json and then convert it to corefile format. But this is not the case. Isn't text-templating a better workaround then gluing together the file in jsonnet?

**Comment by Duologic** [comment]
That is also a way to look at it, why isn't the Corefile in a more common format? Jsonnet standard lib has several manifestation options: https://jsonnet.org/ref/stdlib.html#manifestation

Anyway, not something we can change overnight 😔

**Comment by curusarn** [comment]
I'm not looking for an overnight change or an instant solution. I'm just trying to argue that templating would be a reasonable way to generate files in Jsonnet in cases where it is impossible to represent the format as Json(net) and then marshall it.

Based on what @sh0rez wrote earlier:
> Hi! Could you elaborate on the use-case? Jsonnet itself is a fairly capable language, so it would surprise me if you run into cases that can't be solved by standard Jsonnet means.
> 
> JSON-similar config formats (TOML, YAML, JSON, INI) can be represented in Jsonnet and marshalled. For other formats, it's often possible to pre-compute the complex part and only string-format it in into place.
> 
> We've considered this before, and always found ways to do it without introducing templating support, but let's see :)

I got an impression that you currently don't want to add templating because so far you always found a better way to generate configs. And that you are willing to reconsider if I there are legitimate use-cases where it makes managing k8s configuration cleaner and more robust.

Considering my example and arguments above, are you opposed to adding templating support to tanka? (I'm willing to implement it.)

**Comment by curusarn** [comment]
not stale, just waiting for reply

**Comment by Duologic** [comment]
I think we are not strictly opposed but it is a feature that is already covered in plain Jsonnet, adding custom templating would diverge our flavor Jsonnet even further from where it is now.
Secondly, as I mentioned I think in this particular case the problem is the poor choice of configuration language chosen upstream, imo this is uncommon and most applications use a more common format that Jsonnet can manifest.
I do agree the templating is rough, but the second example you posted looks quite reasonable, can I suggest breaking the for-loops into multiple lines to increase readability? 
I hope this is a sufficient answer to your question and we can (at least for now) close this for now.
