### ISSUE TITLE
Undefined external variable: tanka.dev/environment

### ISSUE THREAD

**Issue by smuth4** [grafana/tanka#480]
This error occurs on the latest build (works just fine in 0.13.0) when I try to use any of the spec data as per https://tanka.dev/config#jsonnet-access:
```
Error: evaluating jsonnet: RUNTIME ERROR: Undefined external variable: tanka.dev/environment
        <internal>/tk.libsonnet:3:8-43  object <anonymous>
        /home/tanka-test/environments/default/main.jsonnet:7:13-19
        Field "test"
        During manifestation
```
Minimal reproducible example:
environments/default/main.jsonnet
```
local tk = import "tk";
{
  test: {
    apiVersion: 'v1',
    kind: 'Namespace',
    metadata: {
      name: tk.env.spec.namespace
    }
  }
}
```
environments/default/spec.json
```
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "environments/default"
  },
  "spec": {
    "apiServer": "",
    "namespace": "default",
    "resourceDefaults": {},
    "expectVersions": {}
  }
}
```
`tk eval environments/default`, also happens on any other command against it.

**Comment by sh0rez** [comment]
Hi, I verified and reproduces this bug. It will be fixed in #482. Thanks for reporting!

**Comment by smuth4** [comment]
Sorry for the time it took me to circle back around to this, but it looks like this bug still exists for `tk eval`.

For more context, I wanted to put the namespace into a rolebinding's subject dynamically. In my use case, I can `local spec = import 'spec.json';` directly, but it wouldn't work for dynamic environments or tanka specific libsonnets.

**Comment by Duologic** [comment]
You are right.
