### ISSUE TITLE
No `charts add-repo` command available

### ISSUE THREAD

**Issue by szczad** [grafana/tanka#484]
# Version
0.13.0
# Problem
[Official docs](https://tanka.dev/helm#charttool) states that I can add chart repository into the `chartfile.yaml`
```
# Add the official Grafana repository
$ tk tool charts add-repo grafana https://grafana.github.io/helm-charts
```

Well... That's in contradiction to what I have experienced using Tanka:
```
$ tk tool charts
Declarative vendoring of Helm Charts

Usage:
  tk tool charts [command]

Available Commands:
  init        Create a new Chartfile
  add         Adds Charts to the chartfile
  vendor      Download Charts to a local folder
  config      Displays the current manifest

Flags:
  -h, --help   help for charts

Use "tk tool charts [command] --help" for more information about a command.
```

If I try to run the command anyways I get the error:
```bash
$ Error: unknown subcommand `add-repo`
```

**Comment by sh0rez** [comment]
Hey, good spot. The website is built from current `master`, and the commit that adds this functionality has not yet been included in any release.

Please wait for the next release, or built it yourself from `master` :)

**Comment by szczad** [comment]
Oh... But wait... Isn't that a matter of pointing to the right tag to build the docs? :smile:

**Comment by sh0rez** [comment]
Agreed, this leads to slight inconsistencies, but these don't appear frequent enough to justify the extra complexity it imposes on our build pipeline. If this happens a lot in the future, we might reconsider it :)

Closing as 0.14 is released, so this feature is generally available
