### ISSUE TITLE
Unable to fully remove resources if the state was altered

### ISSUE THREAD

**Issue by szczad** [grafana/tanka#485]
Tanka is unable to remove remaining resources if one or more resources defined in the library is missing or could not be deployed to the cluster.

Example:
I have deployed `locki-stack` using the official Helm chart from the repository. One pod for testing did not come up properly so was removed manually. From now on the deployment cleanup fails and cannot be fully removed by Tanka. To fix that I would either have to add the pod by hand, redeploy the stack and remove it again or make a manual cleanup.
```
$ tk delete environments/testing
(...)
Deleting from namespace 'testing' of cluster 'k8s-JgKHLmMd' at 'https://<k8s-server>' using context 'k8s-JgKHLmMd'.
Please type 'yes' to confirm: yes
Error from server (NotFound): pods "asdasd-loki-stack-test" not found
exit status 1
```

This might come very often when developing the deployment code or the code has been altered from the outside (which in fact might be possible if someone made changes like OPS fighting with SEV1 issues impacting the business). 

I would expect to have a switch to control how Tanka behaves when deleting resources (like passing `--ignore-not-found=true` to the `kubectl` process).

**Comment by malcolmholmes** [comment]
what command are you using to do the deletion?

**Comment by szczad** [comment]
```
tk delete <environment>
```

**Comment by sh0rez** [comment]
Hey @szczad, I agree that this is definitely incorrect behavior. Attempting to delete something that does not exist should not be fatal. Instead, it should probably just print to `stderr` that `resourceSomething` does not exist.

The relevant code is located here:
https://github.com/grafana/tanka/blob/2caa67303bcf9b646e462e966ad71896d8cef695/pkg/kubernetes/delete.go#L20-L24

We would need to catch the `Error from server (NotFound): .*` error from kubectl stderr and react accordingly.

Are you interested in contributing a fix to this? We would be there to help you in the process if required :)

**Comment by szczad** [comment]
I don't promise anything. I'll have a look at the source code in my free time.

**Comment by StevenPG** [comment]
@sh0rez let me know if the PR #539 addresses the issue at hand. I'm open to make any changes needed to try to get this issue resolved. It's a blocker for our current tanka workflow and I'd love to do whatever I can to help get the fix upstream. Thanks!

**Comment by StevenPG** [comment]
Keeping issue open since it's still an open issue.
