### ISSUE TITLE
Tanka could validate imports across multiple environments

### ISSUE THREAD

**Issue by malcolmholmes** [grafana/tanka#486]
In running `tk tool imports` across our Tanka environments, I found a number that had imports that weren't used, where the imported file was in fact missing.

It would be useful for Tanka to have the ability to do a scan like this, perhaps it is the beginning of `lint` functionality.

**Comment by sbarzowski** [comment]
I'm thinking about whether we could support that upstream. I was thinking about some kind of runtime record of the imports that were actually requested. This is potentially very useful for smart cache invalidation of Jsonnet outputs.

**Comment by sh0rez** [comment]
So, `tk tool imports` does static AST analysis. Before https://github.com/grafana/tanka/pull/84, it actually did runtime analysis and only reported those that were actually requested, but it used a massacred Jsonnet evaluator for that.

@sbarzowski I really do like the idea of jsonnet being able to tell what imports are used, and caching those that are unchanged sounds incredibly useful. Could you go into more detail on how to get this going? I'd certainly be interested in helping out

**Comment by sbarzowski** [comment]
Sorry I missed your previous message. Got reminded by the bot :-).

>  I was thinking about some kind of runtime record of the imports that were actually requested.

> Could you go into more detail on how to get this going?

So, the idea here would be basically to (a) add API which allows registering callbacks for event "path was imported" (b) create an utility implementation which just collects all of these and saves them to as a slice or something (c) an option for the commandline which uses (a) and (b) to dump these into a file (one import path per line?).

Hmmm... and besides the paths themselves probably we should also calculate hashes if we want to use it for invalidation. And we'll need to keep track of extVars and TLAs as well.

> I really do like the idea of jsonnet being able to tell what imports are used, and caching those that are unchanged sounds incredibly useful.

Unfortunately this only really helps us when none of the files affecting evaluation are changed. It doesn't really help us to know that one import was not changed (we still need to load the ). 

If we run Jsonnet multiple times to produce multiple outputs, we can make sure that we recalculate each output only when files relevant to this particular output file change. 

E.g.

feature_a.libsonnet:
```
std.range(1, 1000)
```
feature_b.libsonnet:
```
std.range(1, 2000)
```
lib.libsonnet
```
local a = import "feature_a.libsonnet",
        b = import "feature_b.libsonnet";
        
{
  a: a,
  b: b
}
```
a.jsonnet (used for a.json)
```
local lib = import "lib.libsonnet";
lib.a
```
b.jsonnet (used for b.json)
```
local lib = import "lib.libsonnet";
lib.b
```

In the example above we could dynamically determine that calculating `a.jsonnet` depends only on `lib.libsonnet` and `feature_a.libsonnet` (and **not** `b.libsonnet`).
