### ISSUE TITLE
tk apply --target CustomResourceDefinition ...

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#489]
similar to #453 I need a way to select all CustomResourceDefinitions to apply first (before applying other manifests). If CRDs are in my jsonnet but not deployed, I get errors like:

```
error: unable to recognize "STDIN": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
```

when attempting to apply instead of a proper diff.

The apply still works though (mostly)

**Comment by sh0rez** [comment]
Hey, this should be possible using `--target` already:

```bash
$ tk apply -t 'CustomResourceDefinition/.+' .
```

See https://tanka.dev/output-filtering for more details on this functionality

**Comment by ghostsquad** [comment]
Oh thanks ok. I didn't know it was regex (maybe that needs to be in the `--help` ?

**Comment by sh0rez** [comment]
Yeah, we should improve the help text. Closing in favor of https://github.com/grafana/tanka/issues/452

**Comment by Duologic** [comment]
related: #246
