### ISSUE TITLE
hide generated fields and default values in diff

### ISSUE THREAD

**Issue by meier-christoph** [grafana/tanka#494]
It would be nice if tanka could filter out some of these fields when doing a diff to make the changes more readable.

There is a plugin called `neat` that does a pretty good job already but I have no idea how this could be integrated with tanka https://github.com/itaysk/kubectl-neat. 

You may also check out https://github.com/kubernetes/kubernetes/issues/90066

**Comment by Duologic** [comment]
You can override the `kubectl` diff command with `KUBECTL_EXTERNAL_DIFF` and exclude whatever you want.

Here is an example that works with Flux:

https://gist.github.com/Duologic/257f52453957c051c3014d2030467ede#file-diff-sh

**Comment by meier-christoph** [comment]
thanks a lot

**Comment by Duologic** [comment]
I believe this resolved your issue.

**Comment by benjvi** [comment]
The script that's needed to render diffs nicely can now be found in this kubectl-neat issue: https://github.com/itaysk/kubectl-neat/issues/98
