### ISSUE TITLE
`kubernetes.Orphaned()` should not write to stdout

### ISSUE THREAD

**Issue by curusarn** [grafana/tanka#496]
I understand that we don't want to leave the user without any feedback during long running operations in `Orphaned()`. However, when I call `tanka.Diff()` as a library function from another project I get unwanted output that I can't get rid of. If seems wrong to have functions produce output when they can be imported and called from other projects.

I propose adding an option (e.g. `stdoutInfo`) to `Orphaned()` and `Diff()` that could be used to control if there will be info printed out to stdout.

**Comment by sh0rez** [comment]
Lets set some expectations first. Our package design permits the `cmd/tk` (cli handling) and `pkg/tanka` (glue code) packages to print to stdout, as they hold the implementation of Tanka as a CLI tool.

Consumers are expected to either use `pkg/tanka` as long as it fits their workflow. Think of this like the Go equivalent of using the `tk` binary in shell scripts. If that is not suitable, the expectation is to use the underlying packages, which in your case would be `pkg/kubernetes`.

Having that said, `pkg/kubernetes` is the thing that actually prints to `stdout` here:
https://github.com/grafana/tanka/blob/315bb096a82154f5c113135000aea95ae56eef2d/pkg/kubernetes/apply.go#L39
https://github.com/grafana/tanka/blob/315bb096a82154f5c113135000aea95ae56eef2d/pkg/kubernetes/apply.go#L61

First of all, this really should be `stderr`, also these really are statements from the phase where `prune` was highly experimental and we wanted to closely watch timings for performance reasons.

Going forward, we could either remove these statements or somehow pass a `log.Logger` / `io.Writer` / logging interface as part of the `*kubernetes.Kubernetes` type. wdyt?

**Comment by curusarn** [comment]
I agree that `pkg/tanka` printing to stdout makes sense.

I don't think it's reasonable to remove the info statement. The operation can easily take a minute to complete and it doesn't feel right to leave users without any feedback for that long. 

Passing a logger to `*kubernetes.Kubernetes` seems like the right solution. 
The question is if we have any other long running operations or if we expect to have them in the future. If not then maybe we could just pass the logger to `Orphaned()`. Not the cleanest solution but maybe it's better than changing how everything in `kubernetes` package is called.

Disclaimer: I have no idea what is the proper way to log from imported packages

**Comment by curusarn** [comment]
For some reason `tk prune` doesn't take as much time as it did in the past for me.

In the past,  `fetching previously created resources` took up to `1m40s`.
I suspect that selecting resources based on labels involved iterating over all resources in the cluster.

Now, with the same cluster I get at most `fetching previously created resources .. done 20.308331916s`.

I don't know what changed exactly. I can/will investigate.
But I'm wondering what times are other people seeing with `tk prune`.
If nobody is getting times that are close to a minute then maybe we could drop the print statements.

What do you think?
Any idea what influences `tk prune` running times?

**Comment by curusarn** [comment]
not stale, still an issue

**Comment by curusarn** [comment]
Explanation why I care about this getting resolved: 

We use tanka to deploy things. We apply changes manually and we have written some tanka-based monitoring that ensures that tanka environments don't stay out of sync with git for too long. We use json as our log format and the stdout messages coming from `Orphaned()` make the logs of the monitoring service incredibly messy.

**Comment by zerok** [comment]
Looks like this was already resolved by introducing zerolog. Please reopen if this is not correct 🙂
