### ISSUE TITLE
Can Tanka Take YAML as input?

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#497]
Can Tanka take yaml files as input? I assume it works fine with `json` (as jsonnet is a superset). I ask because I think it might be a valuable replacement for kubectl when it comes to deploying safely.

**Comment by Duologic** [comment]
There is a [parseYaml native function](https://tanka.dev/jsonnet/native/#parseyaml) that can do that.

**Comment by ghostsquad** [comment]
It would be cool if there was a flag to allow main.yaml or something like that.

**Comment by ghostsquad** [comment]
Oh I see, just make a main.jsonnet that imports a yaml. Let me play around with this

**Comment by sh0rez** [comment]
Yes, a minimal `main.jsonnet` is the way to go. Literally put that thing at the root level:

```jsonnet
std.native('parseYaml')(importstr 'myFile.yaml')
```
