### ISSUE TITLE
tk diff renders no colors

### ISSUE THREAD

**Issue by shibumi** [grafana/tanka#501]
Hi,
I am the tanka maintainer in the Arch Linux repositories.
My tanka version does not render colors in the vscode terminal and in my "alacritty" terminal emulator.
The result looks like this:

![https://kurisu.shibumi.dev/share/img-2021-02-04-17-21-32.png](https://kurisu.shibumi.dev/share/img-2021-02-04-17-21-32.png)

Do you have any idea? Tanka version is 0.13.0

**Comment by Duologic** [comment]
This is most likely a problem with `TERM` being set to something incompatible.

**Comment by shibumi** [comment]
@Duologic  TERM is `xterm-256color`
