### ISSUE TITLE
Add "--inject-labels" option to `tk env add`

### ISSUE THREAD

**Issue by curusarn** [grafana/tanka#504]
I currently need to edit the `spec.json` of each new environment I create (because I always want to `injectLabels`). Since I can specify `--server` and `--namespace` I would also expect to be able to specify `--inject-labels`. 

What do you think?

**Comment by Duologic** [comment]
Have you considered using inline environments? You could then define the labels in Jsonnet and include it everywhere.

**Comment by sh0rez** [comment]
@Duologic IIUC this is not about injecting labels into kubernetes resources, but setting the `spec.injectLabels: true` option in the Environment definition so that `tk prune` works.

If that is correct, than sure, I'm all in for having that. Would you like to contribute that yourself @curusarn?

**Comment by sh0rez** [comment]
Resolved in #505
