### ISSUE TITLE
Feature suggest: Mask secrets in apply stdout

### ISSUE THREAD

**Issue by SergeyKons** [grafana/tanka#512]
Currently, if we run `tk apply` somewhere in CI, job logs will contain all secret value that was added in this apply.

 I think we can mask these values in stdout

**Comment by craigfurman** [comment]
This would be great, but if I understand it correctly the best place to put this masking is in `kubectl diff`, which tanka calls to produce diffs: https://github.com/kubernetes/kubernetes/issues/87840.

My team has very recently started parsing the output of tanka diff, apply, and parse, redacting diff hunks that correspond to k8s Secret objects: https://gitlab.com/gitlab-com/gl-infra/k8s-workloads/tanka-deployments/-/blob/master/suppress-secrets/main.go

I've opened a tanka PR to separate diff and non-diff output onto stdout and stderr, assisting piping into a tool that parses diffs: https://github.com/grafana/tanka/pull/537.

**Comment by Duologic** [comment]
#537 was merged (release coming soon), which should help to resolve this in a custom setup.

@craigfurman Tanka generally just passes along the output from `kubectl`. Another option would be to use `KUBECTL_EXTERNAL_DIFF` and obfuscate secrets through that.

I'm going to close this as I think this is not a problem Tanka should solve.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
This was addressed in upstream kubectl: https://github.com/kubernetes/kubernetes/pull/96084.
