### ISSUE TITLE
Tanka enviroment listing order is not stable

### ISSUE THREAD

**Issue by curusarn** [grafana/tanka#524]
This is a nitpick but since `v0.14.0` the order of `tk env list` is not stable.

This produces a non-empty diff:
`tk env list --names > /tmp/1 && tk env list --names > /tmp/2 && diff -u /tmp/{1,2}`

I suspect that changes related to inline environments have caused this.

**Comment by sh0rez** [comment]
Hey, I noticed this as well, but forgot to publish the PR. Done so now :D

**Comment by Duologic** [comment]
I've addressed this in #521, which is already in master.

**Comment by Duologic** [comment]
As per #521, resolved.
