### ISSUE TITLE
String escaping

### ISSUE THREAD

**Issue by hrvolapeter** [grafana/tanka#527]
There seems to be difference between jsonnet and tanka string escaping.
Use case I have jsonnet object containing templates from tekton which include new lines and are evaluted at run time. I would like to be able to generate yaml with:
``` yaml
a: '$(params.body)'
```
or
``` yaml
a: |-
 $(params.body)
```
## Current behaviour
``` jsonnet
{
 a: '$(params.body)'
}
```
which is translated to 
``` yaml
a: $(params.body)
```
whereas with jsonnet std.manifestYamlDoc it would be:
``` yaml
a: "$(params.body)"
```
the body parameter can contain new lines which tanka is not aware of at compile time. 

I would like to have a way of forcing tanka to use\keep quotes in output.

### Alternative
 I tried `|-` and for some weird reason
``` jsonnet
{
 a: '|- $(params.body)'
}
```
results in
``` yaml
a: |-
 |- $(params.body)
```
where I would expect this just not work, but not duplicate "text block" definition the same happens with `|` `>` `>-`

**Comment by sh0rez** [comment]
Is it correct we are talking about the output `tk show` gives when rendering your Jsonnet?

If so, here is how it works:
- The Jsonnet VM hands us JSON
- We analyze that JSON to extract any Kubernetes objects, etc
- We render that using `yaml.Marshal` (`gopkg.in/yaml.v2`)

You are seeing specifics of that YAML library here. By default, strings are not quoted, unless it becomes required for semantic reasons. E.g. a multiline string would automatically `|-`.

So unless I miss something, it looks to me like there is no actual problem?
