### ISSUE TITLE
Run tanka inside the cluster and use service account token

### ISSUE THREAD

**Issue by raynix** [grafana/tanka#530]
Hi team,

I tried to use tanka in my github runner which runs in my cluster. Different to kubectl which can pick up /run/secrets/kubernetes.io/serviceaccount/token and connect to kubernetes cluster API tanka relies on kubectl context(which doesn't exist in a container). Is there a way to tell tanka to use the service account token?

Currently I use a workaround:
```
tk show environments/default/ --dangerous-allow-redirect  |kubectl apply -f -
```
Please advise.

Thanks.
Ray

**Comment by Duologic** [comment]
I often hear Tanka users implementing a CD solution like Flux or ArgoCD that reads the plain manifests generated by `tk export`. These CD solution are arguably more suited to run inside a cluster. Tanka was not build with that in mind and we currently don't have plans to turn this into a CD solution.

In case you still want to go through with it, you could devise a KUBECONFIG that uses the service account, have a look here for inspiration: https://stackoverflow.com/questions/55629894/kubernetes-kubeconfig-with-service-account-token

**Comment by raynix** [comment]
@Duologic thanks for the explanation, I'll have a look at ArgoCD.
