### ISSUE TITLE
diff sub-command fails with mysterious error when kubectl version is < 1.18.0

### ISSUE THREAD

**Issue by findmyname666** [grafana/tanka#532]
Hello all,

**diff** sub-command fails with mysterious error when **kubectl** version is < **1.18.0**.
The error message: **exit status 1**.

I notice this [if condition](https://github.com/grafana/tanka/blob/31cda44cafe29dfb857574b54d135732527b8411/pkg/kubernetes/client/diff.go#L65) while debugging the code. It completely hide the real reason why it is failing ...

**diff** is working fine after **kubectl** upgrade.

BR

**Comment by Duologic** [comment]
Looks similar to https://github.com/grafana/tanka/pull/539
