### ISSUE TITLE
`tk export --selector` behaviour is suprising

### ISSUE THREAD

**Issue by limoges** [grafana/tanka#554]
I've been using `tk export` quite aggressively in combination with ArgoCD.

The manifest export pattern is the most important for me as I get flat manifests and can easily restructure deployments overtime.

Unfortunately, `tk export -l/--selector` simply doesn't look to be working. I might also be misunderstanding the purpose of the selector.

I've tested with:
- `0.14.0`
- `0.15.0`

I've setup a small example to reproduce here:
https://github.com/limoges/tk-export-example

**Comment by limoges** [comment]
Looking through the code in search of a bug, it seems the `selector` might be a bit of a mis-documented feature:
https://github.com/grafana/tanka/blob/17da685bbff3baee75e529b13c19d8f047015395/pkg/tanka/export.go#L41

I would have expected it to filter for resources but instead it seems we filter environments based on labels.

**Comment by captncraig** [comment]
That is correct. There isn't a good way to filter resources by labels that I know of.

**Comment by limoges** [comment]
I've renamed the issue as it seems to be "working-as-intended".
