### ISSUE TITLE
Is it possible to pipe the output of export (to kubeseal for example)?

### ISSUE THREAD

**Issue by nagyv** [grafana/tanka#560]
Hi!

I would like to use `tk export` to populate the manifest repo of a tool, like the GitLab Kubernetes Agent. The repo should never store plain secrets, so I use `kubeseal` to encrypt them. 

I can run `tk export -t 'secret/.*'` to export only the secrets, but it requires the output directory. Is there a way to pipe the output instead to a command, like `kubeseal`?

**Comment by Duologic** [comment]
That is possible with `tk show --dangerous-allow-redirect`. The dangerous keyword is mostly to discourage piping `tk show | kubectl` as `tk apply` is much more reliable for this purpose.
