### ISSUE TITLE
Custom ordering of resource creation / deletion

### ISSUE THREAD

**Issue by CrawX** [grafana/tanka#564]
First of all I'd like to thank Grafana Labs and the community around it for yet another brilliant tool! Using this feels like a very promising alternative to Helm or Terraform for Kubernetes deployments.

I'm using Tanka to deploy CRDs for [AWS App Mesh controller](https://github.com/aws/aws-app-mesh-controller-for-k8s) which in turn creates objects in AWS App Mesh. The [CRDs](https://aws.github.io/aws-app-mesh-controller-for-k8s/reference/api_spec/) reference eachother (ie. a `GatewayRoute` references a `VirtualService`). Deleting a `VirtualService` while there are still `GatewayRoute`s linked to it, causes the controller to block the deletion which somehow results in Tanka being unresponsive until I close it via CTRL^C.

Is there any way I can instruct Tanka to delete resources only after certain other resources have been deleted? In my use-case this could work by prioritizing whole `Kind`s of resources, but ideally I would want it to work on a per-resource-basis.

Even though the controller seems to handle creation of the CRDs in the "wrong" order better, this could probably still help for creation as well.

The way I fixed this for now is deleting the objects manually via the AWS Console and then removing them via kubectl (which is also blocked by the controller but is more "flexible" in terms of ordering).

I tried checking the docs and the other issues but couldn't find anything that would help me here, if there's something I missed, I'd be happy to try.

**Comment by Duologic** [comment]
Thank your for the report.

I believe this is quite similar to https://github.com/grafana/tanka/issues/246, also there the ordering was suggested.

**Comment by CrawX** [comment]
Hi @Duologic, yep there are definitely some similarities but I feel #246 is more around prioritizing CRDs in general and not how to sort individual resources versus one another. If you prefer, you can close this and I can voice my input in the existing issue.

How could resource-specific ordering be implemented in a Tanka-idiomatic way? I can imagine a few variants:
- adding a `dependsOn` or similarly named explicit field to the definitions that is not rendered to the output like Terraform does
- adding some configuration (file or parameters) that defines the order of CRDs and/or individual resources
- implicitly deriving the dependencies via references in the input (like Terraform does), although this doesn't help with use cases where resources dont't depend on values from depending resources (which is probably why `depends_on` exists in Terraform)

Pretty sure there are other, more idiomatic ways. I would consider working on the implementation if the general direction makes sense...

**Comment by Duologic** [comment]
I don't have an immediate answer to that, my gut feeling says it should be part of the Environment's spec. It could have an ordered list of manifests that should be applied before anything else.

It is different than #246, but I think it will touch nearly the same code and should probably be designed for together with this issue.

At Grafana, we use Flux to apply exported manifests to the cluster. This reduces the need for working on this on our end but we gladly want to collaborate and accept community contributions.

**Comment by CrawX** [comment]
I'm leaning towards combining tanka (or just jsonnet) with a GitOps tool like Flux or ArgoCD (like @Duologic mentioned, thanks for the input) which will probably solve a bunch of other, unrelated issues.

I'm closing this for now.
