### ISSUE TITLE
Cannot reference custom format in spec.json with tanka export

### ISSUE THREAD

**Issue by filipposc5** [grafana/tanka#567]
`tk version v0.14.0`
I am trying to recursively export environments (not inline environments).

I have added custom metadata in various places inside spec.json but for some reason I cannot seem to reference them when using the `tk export --format` command. I can only reference `apiServer` attribute.
For example:
```
flux/prometheus/monitoring/prometheus-flux/spec.json
@@ -2,7 +2,8 @@
   "apiVersion": "tanka.dev/v1alpha1",
   "kind": "Environment",
   "metadata": {
-    "name": "flux-abc"
+    "name": "flux-abc",
+    "clustername": "foo"
   },
   "spec": {
```
then using 

```
bin/tk export foo5 flux/  --format '{{.metadata.clustername}}/{{.apiVersion}}.{{.kind}}-{{if .metadata.namespace }}{{.metadata.namespace}}-{{end}}{{.metadata.name}}' -r
Error: File 'foo5/<no value>/v1.ServiceAccount-monitoring-prometheus-flux.yaml' already exists. Aborting
```
I have tried `environment.metadata.clustername` `env.metadata.clustername` or even adding it under `spec` section, however it always results to `<no value>` so I am wondering what I am missing here.

Is spec.json not the correct place to put this ?

**Comment by Duologic** [comment]
`metadata.clustername` is not part of the [spec](https://github.com/grafana/tanka/blob/main/pkg/spec/v1alpha1/environment.go), so Tanka won't recognize it.

I suggest using labels instead, those get exported just fine.
