### ISSUE TITLE
Unexpected filename when using export with kubernetes recommended labels

### ISSUE THREAD

**Issue by dewe** [grafana/tanka#568]
I'm trying to use `tanka export` with a `--format` string that references a [Kubernetes common label](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) `app.kubernetes.io/name`.

I've verified that 

```
{{index .metadata.labels "app.kubernetes.io/name"}}
```
is valid and works with golang templates, but from tanka I just get `<no value>`.

**Comment by dewe** [comment]
This is where the replacement too aggressive: https://github.com/grafana/tanka/blob/60775d3573df333d1076a68f165d8c9ff4acd8b3/pkg/tanka/export.go#L178

Is it ok if I fix this in a PR?

**Comment by Duologic** [comment]
I do not completely understand the problem, can you be a bit more verbose on how to reproduce this?

**Comment by dewe** [comment]
Of course.

Given a resource with label `app.kubernetes.io/name`, like so:

```jsonnet
{
  apiVersion: 'v1',
  kind: 'ServiceAccount',
  metadata: {
    name: 'account',
    labels: {
      'app.kubernetes.io/name': 'website',
    },
  },
}
```

When running

```
$ tk export exportDir environments/test \
  --format='{{index .metadata.labels "app.kubernetes.io/name"}}-{{.metadata.name}}-{{.kind}}'
```

I expect to see a file named

```
website-account-ServiceAccount
```

but instead I get

```
<no value>-account-ServiceAccount
```

And the reason for this is that the `/` in the label name in the template is being handled like a path separator.
