### ISSUE TITLE
Target diff/apply resources by json path

### ISSUE THREAD

**Issue by tskinn** [grafana/tanka#569]
I know we can now target resources by Kubernetes resource / name and that there talks about [targeting by label selector](https://github.com/grafana/tanka/issues/453) but I think I would like to apply by json path.

For example, I like to use self documenting deeply nested resources as recommended in the tanka.dev jsonnet tutorial and I'd like to target groups of resources by how they are grouped in jsonnet. As a basic example, in the [tutorial](https://tanka.dev/jsonnet/main#deeply-nested-object-recommended), I would run something like `tk apply --json-target .web.nginx` to apply the nginx deployment.

Would there be value in pursuing this as a feature? The current target parameter is valuable but I think there is still room for more target-like features.

~~On a related note I find myself putting not only more than one application in an environment but an entire (small) k8s clusters worth of resources in a tanka environment. I just read that it is not recommended to put resources from multiple namespaces in one environment. So is the rule of thumb that environments map roughly to namespaces? Am I heading towards disaster? Do we know how many resources tanka can handle in one environment before it becomes tediously slow? I just like the idea of, similar to terraform, running one command and having an entire dev environment in sync but also being able to target specific resources when necessary.~~

Edit: ^^ moved to https://github.com/grafana/tanka/discussions/570

**Comment by Duologic** [comment]
That last paragraph would fit perfectly into the discussions section, plenty of advice to give on that topic.

I'm not opposed to the idea of applying by path, the code that currently supports this in `tk eval -e path.to.object` and inline environments has its issues, mainly [breaking Top-level arguments](https://github.com/grafana/tanka/issues/522). If we implement this, we need to clearly document which features don't work.

**Comment by malcolmholmes** [comment]
@Duologic This jsonpath approach wouldn't, unfortunately, replace `eval -e` because it wouldn't be able to reach hidden elements, as it would be applied to the resulting json which would already have excluded them.

**Comment by Duologic** [comment]
That is an excellent point, there are at least 2 ways of implementing this:
- Match json-target to the rendered Json (what @malcolmholmes suggests)
- Only render the json needed for json-target (what I suggested)

I guess both have their merits and flaws.

**Comment by tskinn** [comment]
I would definitely want to reference hidden objects. For example

```
{
  _config:: {
    somethingHidden: <evaluated thing>,
  },
  targetedResource: {
    configurableThing: self._config.somethingHidden,
  }
}
```

It sounds like this would not work if we only render the json needed? or am I misunderstanding that?

**Comment by tskinn** [comment]
Would a reasonable solution involve storing the path while [walking the json](https://github.com/grafana/tanka/blob/main/pkg/process/extract.go#L32-L92) looking for kubernetes api objects so they can the api objects can be filtered before the tanka operation?

**Comment by Duologic** [comment]
If you want to access `tk eval -e targetedResource`, above example would work in either solution.  Accessing `tk eval -e _config` would not work in solution one as _config does not show up in the rendered JSON.
