### ISSUE TITLE
Integrate `jsonnet-lint` as `tk lint`

### ISSUE THREAD

**Issue by josephglanville** [grafana/tanka#571]
After `jsonnetfmt` was implemented in Go it was integrated into Tanka with the `tk fmt` subcommand.

It would be great if the same could be done for `jsonnet-lint` as it's also Go and would save on needing to export the Jsonnet path and run the tool manually.

Doing so will make linting more accessible and feel like a more integrated experience.

**Comment by Duologic** [comment]
Duplicate of https://github.com/grafana/tanka/issues/342
