### ISSUE TITLE
[BUG] Functions are not referentially transparent when using the root "$" variable.

### ISSUE THREAD

**Issue by Jezza** [grafana/tanka#586]
I can't tell if this is an issue with jsonnet specifically, and how functions work, or if it's related to tanka.

In a nutshell, the following jsonnet snippet, doesn't evaluate correctly.
```
local functions = {
	new(value): {
		value: $[value],
	}
};

{
	my_injected_value: "injected",
	test0: {
		value: $["my_injected_value"],
	},
	test: functions.new("my_injected_value"),
}
```

The "root" ($) isn't fully populated as it's being copied/evaluated, whereas from my understanding, it would be lazily evaluated.

**Comment by Jezza** [comment]
A workaround that I've found is to pass the root ($) variable into the function.
Not pretty, but it gets past the issue.

**Comment by Jezza** [comment]
A simpler workaround if you're operating on the root level already, then you can just refer to self from within the function.

But again, assuming you're already on the root level.

**Comment by sbarzowski** [comment]
The behavior is correct. `$` is just a syntax sugar for a local variable everywhere where you have an object literal (`{ ... }`) that isn't itself contained in an object literal.

So, in your case, this is basically:
local functions = local $ = {
	new(value): {
		value: $[value],
	}
}; $;

local $ = {
	my_injected_value: "injected",
	test0: {
		value: $["my_injected_value"],
	},
	test: functions.new("my_injected_value"),
}; $

You don't see the original `$` in your called function just as you don't see other local variables (i.e. there is no dynamic scoping). If you want to have something in a function either pass it as an argument or capture it in a closure.

**Comment by Jezza** [comment]
Ah, that makes the behaviour a lot clearer.

Many thanks!
