### ISSUE TITLE
[Feature Request] Build upon importstr from jsonnet

### ISSUE THREAD

**Issue by Jezza** [grafana/tanka#587]
One thing that I've found myself doing quite regularly is creating configmaps from folders.

As it stands now, I have to manually create a key for each file, and then `importstr` the file directly.  
This leads to very unmaintainable code as it ends up just being a bunch of paths.

To make matters worse, importstr only [accepts a string literal](https://github.com/google/jsonnet/blob/master/core/parser.cpp#L841).  
Meaning, I can't make abstract this stuff away.

The end result being, what is quite easy with kubectl, becomes difficult with tanka/jsonnet.  
`kubectl create configmap config-de --from-file ./configs-de/config/`

The workaround, if possible, would solve it:

`importdir './directory/'` (bikeshedding not withstanding.)

It'll just create a json object/map, with each key being the file name, and the content as the values.  
I don't know if it's possible to implement this on tanka's level, or if it would need to go into jsonnet itself.

**Comment by Duologic** [comment]
I would propose it upstream for Jsonnet itself, it wouldn't make as much sense if only Tanka implements this and not other Jsonnet tools would.

**Comment by Jezza** [comment]
It seems there's an ongoing discussion about it upstream.
I'll close this in favour of that.

google/jsonnet#196
