### ISSUE TITLE
Feature request - Accept raw jsonnet on stdin

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#594]
The expectation would be that the raw jsonnet includes the "spec" (spec.json) manifest as well as any other Kubernetes manifests that need to be applied.

**Comment by ghostsquad** [comment]
Not stale

**Comment by Duologic** [comment]
It is possible to accept stdin in jsonnet, which in turn could be jsonnet:

```
➜ cat a.jsonnet
import "/dev/stdin"

➜ echo "{a:'b'}"| tk eval a.jsonnet
{
  "a": "b"
}
```
In combination with inline environments, it can include the spec.json data.

**Comment by ghostsquad** [comment]
Refresh
