### ISSUE TITLE
Allow secret `data` values to be redacted/hashed from diff 

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#602]
This is a request to redact (or sha256) the base64 data values in vanilla k8s secrets when showing the diff.

Along the lines of #594 if the manifests (including secrets) are dynamically generated (in memory), secrets can remain safe if the base64 values never are printed to the screen, and never remain on disk.

**Comment by ghostsquad** [comment]
Not stale

**Comment by Duologic** [comment]
I'd say this is out-of-scope for Tanka.
