### ISSUE TITLE
diff/apply fails for inline-environments when a spec.json is in the same directory

### ISSUE THREAD

**Issue by rrichardson** [grafana/tanka#612]
Not sure if this is a bug or an intended behavior.  But when a spec.json is next to my main.jsonnets, I get this error: 

```
error: unable to recognize "STDIN": no matches for kind "Environment" in version "tanka.dev/v1alpha1"
Error diffing: exit status 2
```

To Repro: 

Put a valid spec.json into a directory next to whatever jsonnet you're using to deploy with tanka. 
run 
`tk apply  ... that.jsonnet `

**Comment by Duologic** [comment]
The error message could be improved, for sure.
