### ISSUE TITLE
std.thisFile returning empty string 

### ISSUE THREAD

**Issue by RixTmobilender** [grafana/tanka#623]
Apologies if this issue is best served in the upstream jsonnet repo.
I believe I'm hitting a bug where `std.thisFile` is returning an empty string, I can't intantiate helm correctly due to this behavior. 

the following snippet:
```jsonnet
helm+: {
  local tanka = import "github.com/grafana/jsonnet-libs/tanka-util/main.libsonnet",
  local helm = tanka.helm.new(std.thisFile),
  executable: helm,
  debug_field: std.thisFile,
  charts_folder: "./charts/", // this is relative to the file where we instantiate executable (right here above)
},
```

is producing:
```json
"helm": {
  "charts_folder": "./charts/",
  "debug_field": "",
  "executable": {
    "#new": {
      "function": {
        "args": [
          {
            "default": null,
            "name": "calledFrom",
            "type": "string"
          }
        ],
        "help": "`new` initiates the `helm` object. It must be called before any `helm.template` call:\n \u003e ```jsonnet\n \u003e // std.thisFile required to correctly resolve local Helm Charts\n \u003e helm.new(std.thisFile)\n \u003e ```\n"
      }
    },
    "_config": {}
  }
},
```

Any idea why this might occur and if it's related to tanka?
The rest of my snippet for reference
[launcher.jsonnet.txt](https://github.com/grafana/tanka/files/7327098/launcher.jsonnet.txt)
 
Actually trying to use the instantiated helm to template results in an error code:
`Error: evaluating jsonnet: RUNTIME ERROR: helmTemplate: 'opts.calledFrom' is unset or empty.`

I'm currently working around this by manually writing the filepath to the current file, it works flawlessly.

**Comment by Duologic** [comment]
Did you try it with plain jsonnet?
