### ISSUE TITLE
Misleading explanations in native functions page

### ISSUE THREAD

**Issue by tsekine354** [grafana/tanka#632]
https://tanka.dev/jsonnet/native has bad letter cases.

For example, [`parseJson`](https://tanka.dev/jsonnet/native#parsejson) has

```
parseJSON(string json) Object
```
(`JSON` is all upper case), while its native function call is

```
std.native('parseJson')('[0, 1, 2]'),
```
(snakeCase).

All functions who have `JSON` or `YAML` in their name have the same issue.

**Comment by saurabh042** [comment]
Hi @tsekine354 I would like to work on this. Could you please assign this to me? Also could you please confirm that we need to update Json or Yaml occurrences to uppercase?
