### ISSUE TITLE
tk apply --force seems to be a noop

### ISSUE THREAD

**Issue by BeyondEvil** [grafana/tanka#652]
```
$ tk --version
tk version v0.19.0

$ tk apply deploy/environments/local/ --force
Warning: There are no differences. Your apply may not do anything at all.
Applying to namespace 'default' of cluster 'kind-kind' at 'https://127.0.0.1:6443' using context 'kind-kind'.
Please type 'yes' to confirm: yes
service/flatter unchanged
deployment.apps/flatter unchanged
```

I would expect both service and deployment to be re-applied using the `--force` flag.

**Comment by sh0rez** [comment]
That's actually outside of our control – `--force` merely sets the flag of same name on the `kubectl apply` invocation:

https://github.com/grafana/tanka/blob/36e5ffe0f2b917e2a6e9ac63d968dec169f90c36/pkg/kubernetes/client/apply.go#L13-L15

Also consider `kubectl help apply`:
```
--force=false: If true, immediately remove resources from API and bypass graceful deletion. Note that immediate
deletion of some resources may result in inconsistency or data loss and requires confirmation.
```

**Comment by BeyondEvil** [comment]
Wait, isn't it weird that the help for "apply" is talking about "deletion"?
