### ISSUE TITLE
jsonnetfile.json overrides per inline environment (not per main.jsonnet file)

### ISSUE THREAD

**Issue by mwasilew2** [grafana/tanka#665]
Hi,

I currently don't see a way to configure dependencies overrides per inline environment, only per main.jsonnet file, as outlined in this doc: https://tanka.dev/libraries/overriding#per-environment . If my understanding is correct, the overrides are possible per static environment (since they live in separate dirs/files), but not per inline environment.

For example, if I have staging and production inline environments living in `environments/grafana/main.jsonnet` I cannot use a different version of a jsonnet lib in each inline env.

Am I missing something? Is there another way to achieve that? Or is this just a missing feature that could potentially be added?

Thanks a lot for your great work!

**Comment by Duologic** [comment]
I haven't encountered this problem yet, but there are several jsonnet-y ways to approach this:

1. Have a separate lib/ directory per version, each lib subdirectory can have its own jsonnetfile.json. Imports would look something like this:

```jsonnet
local myapp = {
  dev: import 'myapp/v1.6/main.libsonnet',
  prod: import 'myapp/v1.0/main.libsonnet',
};

{
  envs: [
    {
      data: myapp[cluster.status],
    }
    for cluster in clusters
  ],
}
```

2. Use named dependencies in jsonnetfile.json, this is a fairly manual and maybe hackish set up that relies on legacyImports behavior in jsonnet-bundler, note the `name` attribute that will be turned into symlinks:

```
// jsonnetfile.json
{
  "dependencies": [
      {
        "source": {
          // ...
        },
        version: "v1.0",
        name: "myapp-v1.0"
      },
      {
        "source": {
          // ...
        },
        version: "v1.6",
        name: "myapp-v1.6"
      }
  ]
}
```
