### ISSUE TITLE
Can't open interactive diff utilities via KUBECTL_EXTERNAL_DIFF

### ISSUE THREAD

**Issue by mattwilder** [grafana/tanka#671]
I have a custom diff wrapper that displays diffs using vimdiff. I have included it below for reference.
This wrapper script works perfectly when running `kubectl diff`, however running `tk diff` or `tk apply` with `KUBECTL_EXTERNAL_DIFF` set to this script simply hangs without displaying any information as to why.

Upon further experimentation, it looks like you can't launch any interactive applications via KUBECTL_EXTERNAL_DIFF when using tk.  Why is this the case?

Here is my kubectl diff wrapper: https://gist.github.com/mattwilder/4d0e41be9636df1fc4fedff6f7f2c539

**Comment by mattwilder** [comment]
unstale

**Comment by ghostsquad** [comment]
Probably not stale...
