### ISSUE TITLE
tk tool charts add fails with urls

### ISSUE THREAD

**Issue by wokalski** [grafana/tanka#691]
Might be related to #454 

Here's the error:

```
Adding 1 Charts ...
 OK: https://helm.releases.hashicorp.com/vault@0.19.0
Added 1 Charts to helmfile.yaml. Vendoring ...
Pulling Charts ...
Error: reading chart manifest: open /code/terraform-boundary-sso/infra/vault-tanka/charts/Chart.yaml: no such file or directory
```

Here's how to reproduce it:

```
tk init
jb install github.com/grafana/jsonnet-libs/tanka-util
tk tool charts init
tk tool charts add https://helm.releases.hashicorp.com/vault@0.19.0
```

Assuming you run it in`/code` you should see the same behavior.

**Workaround**

for any dwellers the workaround is to first add the repository inside `chartfile.yaml` and only then run `tk tool charts add` using the repository name (instead of the url)

**Comment by olegmayko** [comment]
you can helm chart via https  using another subcommand as described [here](https://github.com/grafana/tanka/blame/main/docs/docs/helm.mdx#L164-L169)
