### ISSUE TITLE
Support for kubeconfig flag

### ISSUE THREAD

**Issue by mivasile** [grafana/tanka#716]
Is there any possibility to pass the kubeconfig parameter to the kubectl command used by Tanka in the background?
I try to follow [this](https://stackoverflow.com/a/66109188) solution

This can be implemented as a global flag, something like `tk <cmd> --kubeconfig=$KUBECONFIG_DATA`

**Comment by julienduchesne** [comment]
You can configure a new kubeconfig path with the `KUBECONFIG` environment variable

**Comment by mivasile** [comment]
What I am trying to do is to avoid storing a kubeconfig on the filesystem. (security concerns)
And that solution is working fine with `kubectl`. In my case, I will get the kubeconfig data from an HTTP endpoint.

**Comment by julienduchesne** [comment]
Alright, I don't have any objections, but it'll be probably be a pretty big change. Contributions are welcome

In the meantime, a tempfile would probably be not too bad, right? You could even create a ramdisk, download the file to it and dump the whole thing once tk has finished running. It would never reach the FS

**Comment by zerok** [comment]
IMO this should be solved with a ramdisk and a temporary file in there 🙂 I'll close this issue. Please reopen if necessary 🙂
