### ISSUE TITLE
linting fails on a fresh project

### ISSUE THREAD

**Issue by MatthiasWinzeler** [grafana/tanka#723]
Hi folks

We were excited to see a [lint command being added recently](https://github.com/grafana/tanka/pull/592) and are eager to include that in our CI pipelines.

However, I noticed that linting fails on a fresh tanka project.

Steps to reproduce:

```bash
$ tk --version
tk version v0.22.1

$ mkdir tk-sample
$ cd tk-sample

$ tk init
GET https://github.com/jsonnet-libs/k8s-libsonnet/archive/12ea89d1fa76e716565b2885492da3163e62dd90.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/63274170cdeca59bc33d0f4be61efc6bd5bbb669.tar.gz 200
Directory structure set up! Remember to configure the API endpoint:
`tk env set environments/default --server=https://127.0.0.1:6443`


# setup sample app using default k.libsonnet
cat > environments/default/main.jsonnet <<EOF
local k = import "k.libsonnet";
{
    podinfo: k.apps.v1.deployment.new(
        name="podinfo",
        replicas=1,
        containers=[k.core.v1.container.new(
            name="podinfo",
            image="stefanprodan/podinfo"
        )]
    )
}
EOF

# run lint:
$ tk lint environments/default/main.jsonnet
...
/path-to/tk-sample/vendor/github.com/jsonnet-libs/k8s-libsonnet/1.20/_custom/volumeMounts.libsonnet:1:11-43 couldn't open import "doc-util/main.libsonnet": no match locally or in the Jsonnet library paths

local d = import 'doc-util/main.libsonnet';


Error: Linting has failed for at least one file
```

If i add the docsonnet library to the project, the error disappears:

```
$ jb install https://github.com/jsonnet-libs/docsonnet/doc-util
GET https://github.com/jsonnet-libs/docsonnet/archive/fedfb4920fae931a27190df0aeec5ef858daf3b5.tar.gz 200

$ tk lint environments/default/main.jsonnet
echo $?
```

What's your recommendation - should we add that library to the jsonnet projects?
docsonnet's README explicitly states that this should not be required:

> Do my projects need to have doc-util installed to vendor/?
> No! The `docsonnet` binary comes included with it, and during normal Jsonnet use the docsonnet keys will never be accessed, so your Jsonnet runs just fine without.

https://github.com/jsonnet-libs/docsonnet#do-my-projects-need-to-have-doc-util-installed-to-vendor

If yes, it might be a good idea to add it to the default `tk init` setup, so that future users can use `tk lint` right out of the box.

**Comment by julienduchesne** [comment]
Might be nice to add a caveat in the docsonnet repo indeed. Linting cannot work with inaccessible imports

**Comment by MatthiasWinzeler** [comment]
@julienduchesne I'll happily create a PR to add a notice into the docsonnet repo README.

For our projects, we solved the linting issue by adding docsonnet manually. 

Should tanka install this dependency automatically when creating new projects with `tk init`? If yes, I'd create a PR.

**Comment by julienduchesne** [comment]
> @julienduchesne I'll happily create a PR to add a notice into the docsonnet repo README.
> 
> For our projects, we solved the linting issue by adding docsonnet manually.
> 
> Should tanka install this dependency automatically when creating new projects with `tk init`? If yes, I'd create a PR.

I think both a notice and installing the dependency automatically with `tk init` would be reasonable. This has caused other issues in the past
