### ISSUE TITLE
Website nav menu borked on mobile

### ISSUE THREAD

**Issue by leetrout** [grafana/tanka#732]
The hamburger menu is not working on mobile. I am on an iphone se. 

![E7AEB5A4-FFF5-4079-BF2C-2ACB0723BC75](https://user-images.githubusercontent.com/524648/179352372-a42a4361-d46b-41d9-844d-77b09c5e97aa.png)

https://user-images.githubusercontent.com/524648/179352364-f81cce6e-0455-4cb1-a091-e9995971244c.MOV

**Comment by godwhoa** [comment]
I'm guessing it's [an issue with the outdated docz library](https://github.com/doczjs/docz/issues/495). I gave upgrading it a try but went down the rabbithole of upgrading gastby and all other dependencies. 😬 Gave up in the end.

**Comment by julienduchesne** [comment]
Upgrading docz did not fix it unfortunately. I don't know much about this Gatsby stuff 😕

**Comment by leetrout** [comment]
Thanks for looking.

I tried it on my desktop and I can recreate the same behavior so that is good since it will be easier to test.

When I move the window very slowly from wide to narrow I can see the sidebar animate away and I see `translateX(-100%)` in the CSS. I will take a look when I have a free moment if no one else gets here first. Hopefully just a simple state bug where a class is missing or something since the menu click is making the shaded overlay pop.
