### ISSUE TITLE
Filter `tk diff`-output?

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#736]
Hi,

when running `tk diff..` i noticed a lot of mostly unrelevant fields e.g. the whole `managedFields`-part which makes the diff harder to read. 
Would be nice if this could be somehow filtered out or ignored. Either by cli-parameter or automatically.

regards,
strowi

**Comment by julienduchesne** [comment]
You can set a `KUBECTL_EXTERNAL_DIFF` script to filter out fields that you do not want to consider or see. At Grafanalabs, we have a bash script that passes the diff output through https://github.com/sh0rez/kubectl-neat-diff

**Comment by strowi** [comment]
Thank you, that looks much better. I was fiddling with sth. like `export KUBECTL_EXTERNAL_DIFF="diff <(kubectl-neat -f \$1) <(kubectl-neat -f \$2)"` but the provided link works much better.;)
