### ISSUE TITLE
Can't use YAML tags

### ISSUE THREAD

**Issue by WoozyMasta** [grafana/tanka#741]
Hi, thanks for the wonderful tool!

I'm trying to use yaml tags to integrate with external utilities like [age](https://github.com/FiloSottile/age)
But I ran into a data serialization problem, when I try to specify a tag in a key value, it is always wrapped in quotes.

For example, a simple creation of a secret (notice the `!crypto/age` tag):

```jsonnet
{
  secret(deployment, data={}, type='Opaque')::
    local secret = k8s.core.v1.secret;

    local dataEncoded = {
      [k]: '!crypto/age:Literal %s' % std.base64(std.toString(data[k]))
      for k in std.objectFields(data)
    };

    secret.new(deployment.metadata.name, data=dataEncoded, type=type),
}
```

In the output, the value is always in quotes, which breaks the tag

```bash
tk show environments/test --dangerous-allow-redirect |   yq 'select(.kind == "Secret") | .data' 
```
```yaml
PASSWORD: '!crypto/age:Literal c2VjcmV0'
```

But if you remove the leading exclamation mark, the escaping is not applied.

```jsonnet
      [k]: 'crypto/age:Literal %s' % std.base64(std.toString(data[k]))
```
```yaml
PASSWORD: сrypto/age:Literal c2VjcmV0
```

I tried different ways to fix this but it didn't work for me. I expect the output to be like this:

```yaml
PASSWORD: !сrypto/age:Literal c2VjcmV0
```

So far, I see only one way out, export the files to disk, use a separate utility to replace tags, and only then deploy to the cluster.

Maybe I'm wrong and I'm writing to the wrong project and it's a jsonnet problem, but I think you can help me 🙂

**Comment by WoozyMasta** [comment]
Maybe there is some way to refer to the data from the specification, as it is implemented in the export, for example:

```
{{env.spec.namespace}}
```

https://tanka.dev/exporting/#multiple-environments

**Comment by zerok** [comment]
Hi 🙂 As far as I know, Jsonnet doesn't have tags or something similar since the templating use-cases of tags are solved through functions and variables here. As far as I can tell, your only option would be to create a post-processor for the exporter YAML files as Jsonnet also does not allow to call external tools directly.
