### ISSUE TITLE
Question: how to use the environment data in the library?

### ISSUE THREAD

**Issue by WoozyMasta** [grafana/tanka#748]
Hello. Thanks for the awesome tool!

Perhaps someone can suggest how to use the data from the current environment. More specifically, how can I get the `namespace` name?

I ran into this issue while trying to implement `podAntiAffinity` for `deployment`. I looked at the documentation and tried to search for examples on the Internet, but I did not find an elegant solution.

I understand that I can put it in a separate variable, but why? After all, I already said everything to tanka at the stage of creating the namespace, but I can’t use this data.

```bash
tk env add environments/dev --namespace=dev
```

Example:

```jsonnet
local k = import "ksonnet-util/kausal.libsonnet";

{
  new(name, image,): {

  local container = k.core.v1.container,
  local deployment = k.apps.v1.deployment,
  local spec = k.apps.v1.deployment.spec.template.spec,
  local podAntiAffinity = k.apps.v1.deployment.spec.template.spec.affinity.podAntiAffinity,
  local podAffinityTerm = k.core.v1.podAffinityTerm,

  container:: container.new(name=name, image=image),

  deployment:
    deployment.new(
      name=name,
      replicas=1,
      containers=[self.container],
    )
    + podAntiAffinity.withPreferredDuringSchedulingIgnoredDuringExecution(
        podAffinityTerm.withNamespaces(
          // self.deployment.metadata.namespace
          // RUNTIME ERROR: Field does not exist: namespace
          self.deployment.metadata.name // ok
        )
    ),
  }
}

```

**Comment by WoozyMasta** [comment]
Maybe there is some way to refer to the data from the specification, as it is implemented in the export, for example:
```
{{env.spec.namespace}}
```
https://tanka.dev/exporting/#multiple-environments

**Comment by WoozyMasta** [comment]
If I don't understand something, it might be worth adding an example of how to use it here.

https://github.com/grafana/tanka/blob/cfe9627dcab2321746e5cd2eeb05a6b54a674432/docs/design/tanka.md?plain=1#L226

**Comment by Duologic** [comment]
The namespace value is not known in Jsonnet at `self.deployment.metadata.namespace` unless explicitly set by the user, Tanka will configure the namespace on `tk apply/diff` when running against a cluster.

The namespace should be passed down as an argument in `new(name, image, namespace): {` from the environment to the library.

The design doc you referenced refers to `spec.json` environments and the magic import `import "tk"`, note that this does [not work with inline environments](https://tanka.dev/inline-environments#caveats) (not sure which you use).

The templating for `tk export` refers to the export path for the actual YAML manifests.

**Comment by WoozyMasta** [comment]
Thanks for the clarification
