### ISSUE TITLE
Charts vendoring fails when chart files are deleted

### ISSUE THREAD

**Issue by a-nldisr** [grafana/tanka#749]
tanka version: 0.22.1

**How to reproduce:**

```
tk tool charts init
tk tool charts add stable/mysql@1.6.7
```
This downloads the chart files to a `\charts` directory
Remove the YAML files from this charts directory (by switching branches and deleting unneeded files for that branch for example, vscode does this automatically by the press of a button). Leave the directory. After this you run `tk tool charts vendor`:
`tk tool charts vendor`

You will get error:
```
tanka/charts/mysql/Chart.yaml no such file or directory
```

The issue is not there when you delete the directory. Vendor command works fine then. 

**Work around**
Delete the directory and run:
`tk tool charts vendor`

**Expected result:**
When files are not present, try to retrieve them

I know this is a very specific case, just a report so you are aware.

**Comment by Duologic** [comment]
I think `tk tool charts` claims ownership over the `charts/` directory and no other tools should manage its contents. Can you tell vscode to ignore it?
