### ISSUE TITLE
work when localhost is k8s master node

### ISSUE THREAD

**Issue by daixiang0** [grafana/tanka#77]
tanka always read apiServer from `environments/default/spec.json`, and get kubeconfig by `kubectl config view -o json`, even localhost equal to ip in kubeconfig, it return:
```
Diffing: no cluster that matches the apiServer `https://localhost:6443` was found. Please check your $KUBECONFIG
```

It would be an improvement, if you like this, i feel free to file a PR for this.

**Comment by sh0rez** [comment]
Tanka requires the `spec.apiserver` from `spec.json` to be *literally*  the same as in the `$KUBECONFIG` yaml. We do this to make dead sure nobody ever applies to the wrong cluster.

To apply to localhost, make sure both `spec.json` and the `kubectl config view -o json` output the same

**Comment by daixiang0** [comment]
Take an example, if my master node is 10.180.1.1, and i run `tanka` at it, in all case `localhost` is equal to 10.180.1.1, right?
If support this, I only need to make sure is that i run at master node.

**Comment by daixiang0** [comment]
update

**Comment by sh0rez** [comment]
Hi, so, to solve this:

You usually don't want to run Tanka on your master node directly. Rather you would use your development machine / CI server to invoke Tanka like you use to with `kubectl`. 

In case you are running Kubernetes locally, your endpoint might look something like `https://127.0.0.1:6443`. As long as there is a configured context with that **literal exact address** in `kubectl config view -o json`, Tanka works.  
This strictness is intended to make sure you get what you expect.
