### ISSUE TITLE
go-jsonnet import error

### ISSUE THREAD

**Issue by daixiang0** [grafana/tanka#78]
reproduce:
```
# GO111MODULE=on go mod download
# go build ./cmd/tk
../../sh0rez/go-jsonnet/desugarer.go:27:2: cannot find package "github.com/google/go-jsonnet/parser" in any of:
	/usr/lib/golang/src/github.com/google/go-jsonnet/parser (from $GOROOT)
	/deploy/go/src/github.com/google/go-jsonnet/parser (from $GOPATH)
```

**Comment by sh0rez** [comment]
Hi, it looks like you are running INSIDE of `GOPATH`. Please make sure Tankas source is always located OUTSIDE of `GOPATH`

**Comment by daixiang0** [comment]
oh, it is totally different from helm!
Could i add this in build docs?

**Comment by sh0rez** [comment]
Wait a sec, it looks like there have been actually some changes to `google/go-jsonnet` that could indeed make imports fails ... I will look into it

**Comment by daixiang0** [comment]
also, is there a plan to move sh0rez/go-jsonnet to grafana/go-jsonnet?

**Comment by sh0rez** [comment]
No, not really, rather I would like to use the google upstream again.

Due to recent changes to the official compiler it might be possible to ditch the ugly patch I did to it and use the official version again.

`sh0rez/go-jsonnet` would be archived in that case
