### ISSUE TITLE
Discussion: Jsonnet, Dhall, and other insights

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#787]
Hi Grafana Folks!

I'd like to gain some insight into your use of Jsonnet and/or Dhall, and if you could provide any knowledge/experience with either, such as how you debug problems in the code, problems with the language that need work, things that work really well, etc.

Thank you for your time!

**Comment by Duologic** [comment]
Please use the discussions tab on GitHub for discussions. 😏

**Comment by ghostsquad** [comment]
It's not enabled consistently. Maybe I missed it. I'll reroute this. Thanks!

**Comment by ghostsquad** [comment]
Moved to https://github.com/grafana/tanka/discussions/789
