### ISSUE TITLE
diff --summarize missing diffstat

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#802]
Hi,

trying to get a summary of tk diff i am getting the following error when diffstat is not installed. I thought #769 should've removed the dependency?

```bash
~> tk diff -z -s environments/stagingk8s
Error: invoking diffstat(1): exec: "diffstat": executable file not found in $PATH
~> tk --version
tk version v0.23.1
```

**Comment by julienduchesne** [comment]
It's not released

**Comment by strowi** [comment]
Ah sorry, only saw "merged" but seem to have missed the date by 4 days. ;)
