### ISSUE TITLE
Add documentation for `tk tool importers`

### ISSUE THREAD

**Issue by nabadger** [grafana/tanka#807]
Related to https://github.com/grafana/tanka/pull/771 ...this sounds like an interesting feature and may solve some of the problems we have (slow export times on large repos). We currently do a similar thing based on git changes...but our version is all shell script and rather verbose! :)

It might be nice to have some more complete docs around how we can use this - I think I can work it out as it outputs environments for any imported file you pass it (which I guess comes from git).

---

Side note, I did find some odd behaviour as it follows symlinks

```
tk tool importers environments/podinfo-http/aws.dev/main.jsonnet 
```
```
# Seems to follow symlinks which I've setup in my homedir which might cause issues later on...
~ /home/nb/jsonnet/apps/example-jsonnet/environments/podinfo-http/aws.dev/main.jsonnet
~ /home/nb/work/jsonnet/apps/example-jsonnet/environments/podinfo-http/aws.dev/main.jsonnet
```

**Comment by julienduchesne** [comment]
Added some in this PR: https://github.com/grafana/tanka/pull/871
