### ISSUE TITLE
Feature/marketing request: Add tanka to stackshare

### ISSUE THREAD

**Issue by Almenon** [grafana/tanka#818]
As a Devops Engineer I sometimes use https://stackshare.io to evaluate whether to use a tool. I might compare features between tools or check how many companies use a tool. Adding Tanka to stackshare would help people evaluate whether to use it.

https://stackshare.io/vendors#

For example: https://stackshare.io/helm

Also, I'm wondering what companies use Tanka currently? It looks like grafana and https://blog.codavel.com/declarative-management-of-multiple-kubernetes-clusters-with-tanka-and-jsonnet so far.

**Comment by Elfo404** [comment]
there's a page in stackshare about tanka now
