### ISSUE TITLE
helm: Set `includeCrds` to true by default

### ISSUE THREAD

**Issue by iainlane** [grafana/tanka#829]
# Introduction

With Helm 3, CRDs are not rendered by default when using `helm template`. You've got to pass the `--include-crds` flag to get them.

Tanka knows this already, and provides a way to set it, by setting `includeCrds: true` in the call to `helm.template()`. The default is `false`.

# Proposal

I'd like it if we could consider changing the default and setting it to `true` by default, and have people set it to `false` if they don't want CRDs.

# Why

We just ran into this recently: we upgraded a charm which started following the pattern in its new version and the CRDs went away because they stopped being templated. Given

  * this is the supported way to install CRDs by helm upstream when templating
  * `helm install` installs them by default

I think it makes sense for us to follow suit.

# Why not (maybe)

  * I'm not sure if it is, but it could be more common that people do _not_ want to install the CRDs that come with helm charts than they do. In that case we would want to keep the default as is.
  * The doc referenced below talks about some problems with distributing CRDs, e.g. how you don't necessarily know if they're being used by other workloads. Once you've set `includeCrds: true` we give you in-place upgrades to them when you upgrade the chart. `helm install` doesn't do that so we've already departed from their behaviour. But at least you've had to opt in explicitly to this with current tanka?
  * It would be a compatibility break, users would need to audit the diff after upgrading Tanka and check if they need any new CRDs that are being installed. Mitigations:
    * The feature is marked as experimental.
    * We would make sure to call it out in the release notes.

# Further reading

  * [An upstream discussion doc on CRD handling](https://github.com/helm/community/blob/02798119c4f8a0c02c83caedecd8768a7e68beee/hips/hip-0011.md#no-special-crd-management).
  * [Helm and CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions).

**Comment by Duologic** [comment]
If I read the docs correctly, `helm install` installs the CRDs by default, so I don't see a problem changing the default in Tanks to match that.
