### ISSUE TITLE
tk tool charts vendor does not work with oci:// protocol

### ISSUE THREAD

**Issue by logyball** [grafana/tanka#830]
# Description

When grabbing a chart using the `oci://` protocol and `tk tool charts {subcommand}`, the tool fails.

# Steps to Reproduce

I discovered this when trying to use `tk` with the [Karpenter helm chart](https://gallery.ecr.aws/karpenter/karpenter), which uses the `oci` protocol rather than the more standard `https://`.

Begin with an empty directory and chart project:
```sh
❯ mkdir scratch && cd scratch
❯ tk tool charts init  
Success! New Chartfile created at '<path>/chartfile.yaml'
```

Add a repository with the `oci` protocol:

```sh
❯ tk tool charts add-repo karpenter oci://public.ecr.aws/karpenter/karpenter       
{"level":"info","time":"2023-04-04T09:29:51-04:00","message":"OK: karpenter"}
```

Add the chart:

```sh
 ❯ tk tool charts add karpenter/karpenter@v0.27.1
{"level":"info","time":"2023-04-04T09:30:07-04:00","message":"Adding 1 Charts ..."}
{"level":"info","time":"2023-04-04T09:30:07-04:00","message":"OK: karpenter/karpenter@v0.27.1"}
{"level":"info","time":"2023-04-04T09:30:07-04:00","message":"Added 1 Charts to helmfile.yaml. Vendoring ..."}
{"level":"info","time":"2023-04-04T09:30:07-04:00","message":"Vendoring..."}
{"level":"info","time":"2023-04-04T09:30:07-04:00","message":"Syncing Repositories ..."}
{"level":"info","time":"2023-04-04T09:30:11-04:00","message":"Pulling Charts ..."}
Error: no cached repo found. (try 'helm repo update'): open <path>/karpenter-index.yaml: no such file or directory
Error: exit status 1
```

The same behavior can be observed with the `vendor` subcommand:

```sh
❯ tk tool charts vendor                                                           4s
{"level":"info","time":"2023-04-04T09:31:12-04:00","message":"Vendoring..."}
{"level":"info","time":"2023-04-04T09:31:12-04:00","message":"Syncing Repositories ..."}
{"level":"info","time":"2023-04-04T09:31:16-04:00","message":"Pulling Charts ..."}
Error: no cached repo found. (try 'helm repo update'): open <path>/karpenter-index.yaml: no such file or directory
Error: exit status 1
```

# Background

With the addition of `oci`-based registries, [Helm implemented some changes](https://helm.sh/docs/topics/registries/) and based on the error message I recieved, I believe at least this one will have to be addressed by `tanka`:
- The chart cache has been removed (no helm chart list etc.).

In addition, the `helm repo` subcommand is no longer supported for oci-based registries, which will require some thought about how to handle the [RepoUpdate](https://github.com/grafana/tanka/blob/main/pkg/helm/helm.go#L86) workflow. 

# Impact

Likely not high yet, as `oci` does not seem to be a dominant protocol for charts, but it will grow if and when more charts move there.

**Comment by vtomasr5** [comment]
Same issue when trying to deploy the [grafana-operator](https://github.com/grafana-operator/grafana-operator/tree/master/deploy/helm/grafana-operator) OCI chart.
