### ISSUE TITLE
why not take over the ksonnet project?

### ISSUE THREAD

**Issue by underrun** [grafana/tanka#85]
last i heard maintainers of ksonnet were looking for someone willing to take it over - maybe reach out?

**Comment by malcolmholmes** [comment]
ksonnet and Tanka have different opinions about some things, that are detailed on the [FAQ page](https://tanka.dev/faq/).

For example components, and the use of params. Handing a params object around is unhelpful as it prevents you from overriding them, compared to holding your config/params in a hidden (::) object in your root JSON tree.

Therefore, taking over Ksonnet would either involve shedding these differences, or forcing other Ksonnet users to take on the Tanka approach, neither of which seem optimal.
