### ISSUE TITLE
Let CLI help messages accord to the guidelines

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#91]
There are guidelines how usage strings on the CLI should be formatted: https://en.wikipedia.org/wiki/Command-line_interface#Command_description_syntax

Tanka does not accord to them, but should.

Somebody might want to `grep -R "Use:` the project and reformat all `Use` messages accordingly.
Help is welcome!

**Comment by m1ome** [comment]
If you don't mind i am on it
