### ISSUE TITLE
Manifests not sorted by .metadata.generateName

### ISSUE THREAD

**Issue by ilian** [grafana/tanka#931]
Output of `tanka show` is non-deterministic when multiple manifests are defined when `.metadata.generateName` is defined without `.metadata.name`.
It could be worthwhile to take the value of `.metadata.generateName` into consideration when [sorting](https://github.com/grafana/tanka/blob/v0.26.0/pkg/process/sort.go).

There could be multiple manifests defined with the same `.metadata.generateName` for which the sort order can be non-deterministic. When manifests have different values for this field, then it would be nice to have them sorted.

**Comment by zerok** [comment]
Hi 🙂 I've prepared a PR that should solve this. Can you please give it a look?
