### ISSUE TITLE
tk using wrong kubeconfig context

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#947]
Seems to be a reappearance of https://github.com/grafana/tanka/issues/780 in v0.26.0.

I have 2 contexts 'rancher'  and 'edge-rancher' in my $KUBECONFIG and an `environment/spec.json` with:

```json
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "environments/rancher+argocd"
  },
  "spec": {
    "contextNames": [
      "rancher"
    ],
    "namespace": "argocd",
    "diffStrategy": "native",
    "injectLabels": true,
    "resourceDefaults": {},
    "expectVersions": {}
  }
}
```

And tk always tries to apply to the `edge-rancher` context.

**Comment by zerok** [comment]
Hi 🙂 I hope I found all the relevant places to fix this 🙂

**Comment by strowi** [comment]
Thanks, that was quick @zerok . Looking forward to the next release.;)

**Comment by zerok** [comment]
You're welcome 🙂 Not yet sure when this is going to happen but in the meantime if you need to work with a stable release, then you could try renaming your context to something like `xedge-rancher` or something that would lexically sort after `rancher` 🙂 I hope this will the waiting easier ^_^

**Comment by strowi** [comment]
It's not as big a problem as i thought. Locally i just build your PR und use that. Was thinking about our CI and stuff, which might have multiple contexts. But it only gets a fresh kubeconfig with 1 context each time.
