### ISSUE TITLE
cannot install k.libsonnet using jb

### ISSUE THREAD

**Issue by cameronbraid** [grafana/tanka#95]
I followed the steps at https://github.com/grafana/tanka and it fails with the following error :

```
tk show environments/loki 
Evaluating jsonnet: RUNTIME ERROR: couldn't open import "ksonnet-util/kausal.libsonnet": no match locally or in the Jsonnet library paths
	/Users/cameronbraid/loki-config/vendor/promtail/promtail.libsonnet:1:11-49	thunk <k> from <$>
	/Users/cameronbraid/loki-config/vendor/promtail/promtail.libsonnet:5:1-2	$
	main.jsonnet:1:18-54	thunk <promtail> from <$>
	main.jsonnet:3:1-9	$
	During evaluation	
```

I can see that ksonnet-util is a dependency in vendor/promtail/jsonnetfile.json but it doesn't seem to be installed

**Comment by sh0rez** [comment]
Hi! You are right, it should be installed automatically. However, Tanka does not handle dependencies itself yet, we are using jsonnet bundler for this. Can you check your jb first and if it is okay file an issue with them?

**Comment by cameronbraid** [comment]
https://github.com/jsonnet-bundler/jsonnet-bundler/issues/43

**Comment by cameronbraid** [comment]
According to https://github.com/jsonnet-bundler/jsonnet-bundler/issues/43#issuecomment-541569015 you can't jb install a file

**Comment by sh0rez** [comment]
`jb` was able to do that before, added a comment to your issue. For now, the changes in #96 should resolve that

**Comment by sh0rez** [comment]
This issue is bigger than expected previously. As it will probably need collaboration of both projects, Tanka and jsonnet-bundler, we will need to think thoroughly about the final solution to avoid breaking changes for most users. Discussion is open in #100, closing this in favor of the former one
